import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import pg from "pg";
import { criarRepositorioPostgres } from "../server/db/postgresRepository.js";

const {Client}=pg; const apiUrl=process.env.PRUMO_DATABASE_URL||""; const migrationUrl=process.env.PRUMO_MIGRATION_DATABASE_URL||"";
test("PostgreSQL isola obras, medições e facilities com execução rastreável",{skip:!(apiUrl&&migrationUrl)&&"Conexões PostgreSQL de integração não configuradas."},async()=>{
  const sufixo=randomUUID().slice(0,8),tenantId=randomUUID(),teamA=randomUUID(),teamB=randomUUID(),subject=`teste-execucao-${sufixo}`; const admin=new Client({connectionString:migrationUrl}); const repository=criarRepositorioPostgres({connectionString:apiUrl}); const contextoA={identity:{subject},tenantId,teamId:teamA},contextoB={identity:{subject},tenantId,teamId:teamB};
  try{await admin.connect();await admin.query("INSERT INTO app.tenants (id,nome) VALUES ($1,'Teste Execução')",[tenantId]);await admin.query("INSERT INTO app.teams (tenant_id,id,nome) VALUES ($1,$2,'Equipe A'),($1,$3,'Equipe B')",[tenantId,teamA,teamB]);await admin.query("INSERT INTO app.memberships (tenant_id,identity_subject,perfil_id) VALUES ($1,$2,'administrador')",[tenantId,subject]);await admin.query("INSERT INTO app.team_memberships (tenant_id,team_id,identity_subject) VALUES ($1,$2,$4),($1,$3,$4)",[tenantId,teamA,teamB,subject]);
    const cliente=await repository.criarUnidadePatrimonial(contextoA,{nivel:"cliente",codigo:`C-${sufixo}`,nome:"Cliente"},`c-${sufixo}`);const site=await repository.criarUnidadePatrimonial(contextoA,{nivel:"site",parentId:cliente.id,codigo:`S-${sufixo}`,nome:"Site"},`s-${sufixo}`);const predio=await repository.criarUnidadePatrimonial(contextoA,{nivel:"predio",parentId:site.id,codigo:`P-${sufixo}`,nome:"Prédio"},`p-${sufixo}`);const sala=await repository.criarUnidadePatrimonial(contextoA,{nivel:"sala",parentId:predio.id,codigo:`SL-${sufixo}`,nome:"Sala técnica"},`sl-${sufixo}`);const ativo=await repository.criarAtivoPatrimonial(contextoA,{salaId:sala.id,codigo:`AT-${sufixo}`,nome:"Bomba"},`at-${sufixo}`);
    const orcamento=await repository.criarOrcamento(contextoA,{nome:"Orçamento aprovado da obra",dados:{status:"Aprovado"}},`orc-${sufixo}`);const fornecedor=await repository.criarFornecedor(contextoA,{codigo:`F-${sufixo}`,razaoSocial:"Construtora vencedora",documento:`DOC-${sufixo}`,qualificacao:"qualificado"},`f-${sufixo}`);let processo=await repository.criarProcessoContratacao(contextoA,{orcamentoId:orcamento.id,codigo:`PC-${sufixo}`,titulo:"Licitação da obra",objeto:"Execução da reforma técnica",tipo:"servico",regime:"publico",valorEstimado:50000},`pc-${sufixo}`);for(const acao of ["iniciar_planejamento","abrir_pesquisa"])processo=(await repository.decidirProcessoContratacao(contextoA,processo.id,{acao,dados:{}},processo.versao,`${acao}-${sufixo}`)).processo;await repository.registrarCotacao(contextoA,processo.id,{supplierId:fornecedor.id,valorTotal:45000},`cot-${sufixo}`);for(const acao of ["iniciar_selecao","aprovar"])processo=(await repository.decidirProcessoContratacao(contextoA,processo.id,{acao,dados:{}},processo.versao,`${acao}-obra-${sufixo}`)).processo;const contrato=await repository.criarContrato(contextoA,{processId:processo.id,supplierId:fornecedor.id,codigo:`CT-${sufixo}`,numero:`001-${sufixo}`,titulo:"Contrato da reforma",objeto:"Execução da reforma técnica",dataInicio:"2026-08-01",dataFim:"2026-12-20",valorInicial:45000,dados:{}},`ct-${sufixo}`);await repository.criarBaseContratada(contextoA,orcamento.id,{processoId:processo.id,contratoId:contrato.id,fornecedor:"Construtora vencedora",descontoPercentual:10,justificativa:"Resultado homologado da licitação",itens:[{itemId:"ITEM-1",codigo:"1.1",descricao:"Reforma técnica",unidade:"UN",quantidade:1,precoPublicadoUnitario:50000}]},`base-${sufixo}`);
    let obra=await repository.criarObraCorporativa(contextoA,{patrimonioUnidadeId:sala.id,contractId:contrato.id,orcamentoId:orcamento.id,codigo:`OB-${sufixo}`,nome:"Reforma técnica",dataInicio:"2026-08-01",dataFimPrevista:"2026-12-20",valorPrevisto:50000,dados:{}},`obra-${sufixo}`);obra=(await repository.decidirObraCorporativa(contextoA,obra.id,{acao:"iniciar"},obra.versao,`iniciar-${sufixo}`)).obra;await repository.registrarDiarioObra(contextoA,obra.id,{dataRegistro:"2026-08-02",efetivo:5,atividades:"Mobilização",evidencias:[]},`diario-${sufixo}`);let medicao=await repository.criarMedicaoObra(contextoA,obra.id,{numero:1,periodoInicio:"2026-08-01",periodoFim:"2026-08-31",valorBruto:10000,retencoes:500,glosas:0,multas:0,itens:[],dados:{}},`med-${sufixo}`);medicao=(await repository.decidirMedicaoObra(contextoA,medicao.id,{acao:"enviar"},medicao.versao,`enviar-${sufixo}`)).medicao;medicao=(await repository.decidirMedicaoObra(contextoA,medicao.id,{acao:"aprovar"},medicao.versao,`aprovar-${sufixo}`)).medicao;assert.equal(medicao.status,"aprovada");assert.equal((await repository.listarObrasCorporativas(contextoB)).length,0);
    const plano=await repository.criarPlanoManutencao(contextoA,{ativoId:ativo.id,codigo:`PM-${sufixo}`,nome:"Preventiva da bomba",periodicidadeDias:30,proximaExecucao:"2026-09-01",dados:{}},`pm-${sufixo}`);let chamado=await repository.criarChamadoManutencao(contextoA,{patrimonioUnidadeId:sala.id,ativoId:ativo.id,planoId:plano.id,codigo:`CH-${sufixo}`,titulo:"Inspeção da bomba",descricao:"Vibração observada",tipo:"preventiva",prioridade:"alta",dados:{}},`ch-${sufixo}`);chamado=(await repository.decidirChamadoManutencao(contextoA,chamado.id,{acao:"triar",responsavel:"Equipe"},chamado.versao,`triar-${sufixo}`)).chamado;const ordem=await repository.criarOrdemManutencao(contextoA,chamado.id,{codigo:`OS-${sufixo}`,equipe:"Equipe",dados:{}},`os-${sufixo}`);const custo=await repository.adicionarRecursoOrdemManutencao(contextoA,ordem.id,{tipo:"material",descricao:"Rolamento",unidade:"un",quantidade:2,valorUnitario:100},`rec-${sufixo}`);assert.equal(custo.ordem.custoTotal,200);assert.equal((await repository.listarChamadosManutencao(contextoB)).length,0);
  }finally{await repository.fechar();if(admin._connected){await admin.query("SELECT app.limpar_manutencao_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_ciclo_contratado_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_obras_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_contratos_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_suprimentos_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_patrimonio_tenant_teste($1)",[tenantId]);await admin.query("BEGIN");await admin.query("SELECT app.ativar_contexto($1,$2,$3)",[tenantId,subject,teamA]);await admin.query("DELETE FROM app.orcamentos");await admin.query("DELETE FROM app.domain_events");await admin.query("DELETE FROM app.idempotency_keys");await admin.query("COMMIT");await admin.query("SELECT app.limpar_auditoria_tenant_teste($1)",[tenantId]);await admin.query("DELETE FROM app.team_memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.teams WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.tenants WHERE id=$1",[tenantId]);await admin.end();}}
});
