import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import pg from "pg";
import { criarRepositorioPostgres } from "../server/db/postgresRepository.js";

const {Client}=pg; const apiUrl=process.env.PRUMO_DATABASE_URL||""; const migrationUrl=process.env.PRUMO_MIGRATION_DATABASE_URL||"";
test("PostgreSQL isola e executa o ciclo financeiro completo",{skip:!(apiUrl&&migrationUrl)&&"Conexões PostgreSQL de integração não configuradas."},async()=>{
  const sufixo=randomUUID().slice(0,8),tenantId=randomUUID(),teamA=randomUUID(),teamB=randomUUID(),subject=`teste-financeiro-${sufixo}`; const admin=new Client({connectionString:migrationUrl}); const repository=criarRepositorioPostgres({connectionString:apiUrl}); const contextoA={identity:{subject},tenantId,teamId:teamA},contextoB={identity:{subject},tenantId,teamId:teamB};
  try{await admin.connect();await admin.query("INSERT INTO app.tenants (id,nome) VALUES ($1,'Teste Financeiro')",[tenantId]);await admin.query("INSERT INTO app.teams (tenant_id,id,nome) VALUES ($1,$2,'Equipe A'),($1,$3,'Equipe B')",[tenantId,teamA,teamB]);await admin.query("INSERT INTO app.memberships (tenant_id,identity_subject,perfil_id) VALUES ($1,$2,'administrador')",[tenantId,subject]);await admin.query("INSERT INTO app.team_memberships (tenant_id,team_id,identity_subject) VALUES ($1,$2,$4),($1,$3,$4)",[tenantId,teamA,teamB,subject]);
    const centro=await repository.criarCentroCustoFinanceiro(contextoA,{codigo:`CC-${sufixo}`,nome:"Infraestrutura",dados:{}},`cc-${sufixo}`);const fonte=await repository.criarFonteFinanceira(contextoA,{codigo:`FR-${sufixo}`,nome:"Recursos próprios",tipo:"propria",dados:{}},`fr-${sufixo}`);const orcamento=await repository.criarOrcamentoFinanceiro(contextoA,{costCenterId:centro.id,fundingSourceId:fonte.id,codigo:`ORC-${sufixo}`,descricao:"Plano anual",ano:2026,classificacao:"capex",valorInicial:10000,ajustes:0,dados:{}},`orc-${sufixo}`);let compromisso=await repository.criarCompromissoFinanceiro(contextoA,{budgetId:orcamento.id,codigo:`CF-${sufixo}`,descricao:"Serviço técnico",origemTipo:"manual",competencia:"2026-08-01",valorTotal:10000,dados:{}},`cf-${sufixo}`);assert.equal((await repository.listarCompromissosFinanceiros(contextoB)).length,0);
    for(const [tipo,payload] of [["reserva",{valor:10000}],["compromisso",{valor:10000}],["liquidacao",{valor:10000,retencoes:1000,glosas:500}],["pagamento",{valor:8500,referenciaExterna:"PAG-TESTE"}]])compromisso=(await repository.registrarMovimentoFinanceiro(contextoA,compromisso.id,{tipo,...payload},compromisso.versao,`${tipo}-${sufixo}`)).compromisso;assert.equal(compromisso.status,"pago");assert.equal(compromisso.resumo.pago,8500);const detalhe=await repository.obterCompromissoFinanceiro(contextoA,compromisso.id);const pagamento=detalhe.movimentos.find(item=>item.tipo==="pagamento");await repository.conciliarMovimentoFinanceiro(contextoA,pagamento.id,{referenciaExterna:"EXTRATO-TESTE",status:"conciliado",diferenca:0},`conc-${sufixo}`);assert.equal((await repository.obterCompromissoFinanceiro(contextoA,compromisso.id)).movimentos.find(item=>item.id===pagamento.id).conciliacoes.length,1);
  }finally{await repository.fechar();if(admin._connected){await admin.query("SELECT app.limpar_financeiro_tenant_teste($1)",[tenantId]);await admin.query("BEGIN");await admin.query("SELECT app.ativar_contexto($1,$2,$3)",[tenantId,subject,teamA]);await admin.query("DELETE FROM app.domain_events");await admin.query("DELETE FROM app.idempotency_keys");await admin.query("COMMIT");await admin.query("SELECT app.limpar_auditoria_tenant_teste($1)",[tenantId]);await admin.query("DELETE FROM app.team_memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.teams WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.tenants WHERE id=$1",[tenantId]);await admin.end();}}
});
