import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import pg from "pg";
import { criarRepositorioPostgres } from "../server/db/postgresRepository.js";
const {Client}=pg;const apiUrl=process.env.PRUMO_DATABASE_URL||"",migrationUrl=process.env.PRUMO_MIGRATION_DATABASE_URL||"";

test("PostgreSQL real isola convênios, compliance, BI e portais",{skip:!(apiUrl&&migrationUrl)&&"Conexões PostgreSQL de integração não configuradas."},async()=>{
 const sufixo=randomUUID().slice(0,8),tenantId=randomUUID(),teamA=randomUUID(),teamB=randomUUID(),subject=`teste-finais-${sufixo}`;const admin=new Client({connectionString:migrationUrl}),repo=criarRepositorioPostgres({connectionString:apiUrl});const a={identity:{subject},tenantId,teamId:teamA},b={identity:{subject},tenantId,teamId:teamB};
 try{await admin.connect();await admin.query("INSERT INTO app.tenants(id,nome) VALUES($1,'Teste Sprints Finais')",[tenantId]);await admin.query("INSERT INTO app.teams(tenant_id,id,nome) VALUES($1,$2,'Equipe A'),($1,$3,'Equipe B')",[tenantId,teamA,teamB]);await admin.query("INSERT INTO app.memberships(tenant_id,identity_subject,perfil_id) VALUES($1,$2,'administrador')",[tenantId,subject]);await admin.query("INSERT INTO app.team_memberships(tenant_id,team_id,identity_subject) VALUES($1,$2,$4),($1,$3,$4)",[tenantId,teamA,teamB,subject]);
  const cliente=await repo.criarUnidadePatrimonial(a,{nivel:"cliente",codigo:`C-${sufixo}`,nome:"Cliente"},`c-${sufixo}`),site=await repo.criarUnidadePatrimonial(a,{nivel:"site",parentId:cliente.id,codigo:`S-${sufixo}`,nome:"Site"},`s-${sufixo}`),predio=await repo.criarUnidadePatrimonial(a,{nivel:"predio",parentId:site.id,codigo:`P-${sufixo}`,nome:"Prédio"},`p-${sufixo}`),sala=await repo.criarUnidadePatrimonial(a,{nivel:"sala",parentId:predio.id,codigo:`SL-${sufixo}`,nome:"Sala"},`sl-${sufixo}`);
  let cv=await repo.criarConvenio(a,{codigo:`CV-${sufixo}`,titulo:"Modernização",concedente:"União",convenente:"Federação",objeto:"Modernizar instalações",dataInicio:"2026-01-01",dataFim:"2027-12-31",valorRepasse:100000,valorContrapartida:10000,dados:{}},`cv-${sufixo}`);cv=await repo.decidirConvenio(a,cv.id,{acao:"ativar"},cv.versao,`cv-at-${sufixo}`);await repo.adicionarMetaConvenio(a,cv.id,{codigo:"M-01",descricao:"Reformar",valorPrevisto:90000,dados:{}},`m-${sufixo}`);await repo.registrarRepasseConvenio(a,cv.id,{tipo:"repasse",valor:50000,status:"recebido",dataRealizada:"2026-08-11",dados:{}},`r-${sufixo}`);await repo.registrarExecucaoConvenio(a,cv.id,{dataExecucao:"2026-08-11",descricao:"Etapa 1",valorExecutado:20000,dados:{}},`e-${sufixo}`);assert.equal((await repo.obterConvenio(a,cv.id)).resumo.executado,20000);assert.equal((await repo.listarConvenios(b)).length,0);
  await repo.criarRequisitoCompliance(a,{patrimonioUnidadeId:sala.id,codigo:`REG-${sufixo}`,tipo:"ppci",titulo:"PPCI",numeroDocumento:"PPCI-1",dataValidade:"2026-08-01",criticidade:"alta",dados:{}},`reg-${sufixo}`);await repo.criarRiscoCompliance(a,{codigo:`RSC-${sufixo}`,titulo:"Licença vencida",descricao:"Risco regulatório",probabilidade:5,impacto:5,controle:"Renovação",dados:{}},`risco-${sufixo}`);assert.equal((await repo.obterResumoCompliance(a)).riscosCriticos,1);assert.equal((await repo.listarRequisitosCompliance(b)).length,0);
  await repo.criarDefinicaoRelatorio(a,{codigo:`REL-${sufixo}`,nome:"Diretoria",modulos:["convenios","regularidade"],configuracao:{},compartilhado:true},`rel-${sufixo}`);const acesso=await repo.criarAcessoPortal(a,{tipo:"cliente",nome:"Cliente",email:"cliente@example.com",escopo:{clienteId:"C-1"},expiraEm:"2027-01-01T00:00:00Z"},`portal-${sufixo}`);assert.ok(acesso.token);assert.equal((await repo.listarAcessosPortais(a))[0].tokenHash,undefined);assert.equal((await repo.listarAcessosPortais(b)).length,0);assert.equal((await repo.obterPainelExecutivo(a)).seguranca.isolamento,"RLS");
 }finally{await repo.fechar();if(admin._connected){for(const team of [teamA,teamB]){await admin.query("BEGIN");await admin.query("SELECT app.ativar_contexto($1,$2,$3)",[tenantId,subject,team]);for(const table of ["portal_accesses","report_definitions","integration_channels","transparency_publications","compliance_audits","compliance_actions","compliance_risks","compliance_requirements","agreement_diligences","agreement_accountabilities","agreement_executions","agreement_transfers","agreement_goals","agreements","domain_events","idempotency_keys"]){await admin.query(`DELETE FROM app.${table}`);}await admin.query("COMMIT");}await admin.query("SELECT app.limpar_patrimonio_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_auditoria_tenant_teste($1)",[tenantId]);await admin.query("DELETE FROM app.team_memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.teams WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.tenants WHERE id=$1",[tenantId]);await admin.end();}}
});
