import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { randomUUID } from "node:crypto";
import pg from "pg";
import { criarAplicacaoApi } from "../server/app.js";
import { criarRepositorioMemoria } from "../server/db/memoryRepository.js";
import { criarRepositorioPostgres } from "../server/db/postgresRepository.js";

const { Client } = pg;

const headers=(idempotencyKey="",versao="")=>({"x-prumo-tenant-id":"EMP-1","x-prumo-team-id":"EQ-1",...(idempotencyKey?{"idempotency-key":idempotencyKey}:{}),...(versao!==""?{"if-match":String(versao)}:{})});
async function criarApi(){return criarAplicacaoApi({repository:criarRepositorioMemoria({tenants:[{id:"EMP-1",nome:"Federação",status:"ativo"}],memberships:[{tenantId:"EMP-1",subject:"ADMIN",nome:"Administrador local",perfilId:"administrador",teamIds:["EQ-1"],status:"ativo"},{tenantId:"EMP-1",subject:"ENG-1",nome:"Engenheira de Segurança",perfilId:"gestor",teamIds:["EQ-1"],status:"ativo"}],unidadesPatrimoniais:[{id:"CLI-1",tenantId:"EMP-1",teamId:"EQ-1",nivel:"cliente",codigo:"C-01",nome:"Cliente",status:"ativo"},{id:"SITE-1",tenantId:"EMP-1",teamId:"EQ-1",parentId:"CLI-1",nivel:"site",codigo:"S-01",nome:"Site Centro",status:"ativo"},{id:"PRE-1",tenantId:"EMP-1",teamId:"EQ-1",parentId:"SITE-1",nivel:"predio",codigo:"P-01",nome:"Prédio",status:"ativo"},{id:"SALA-1",tenantId:"EMP-1",teamId:"EQ-1",parentId:"PRE-1",nivel:"sala",codigo:"SL-01",nome:"Sala técnica",status:"ativo"}]}),authenticate:async()=>({subject:"ADMIN"})});}

test("Sprint 31 edita e remove sistemas PPCI preservando inspeções",async(t)=>{const app=await criarApi();t.after(()=>app.close());let r=await app.inject({method:"POST",url:"/v1/regularidade/ppci",headers:headers("p1"),payload:{patrimonioUnidadeId:"PRE-1",codigo:"PPCI-01",titulo:"PPCI principal",dados:{}}});assert.equal(r.statusCode,201,r.body);const ppci=r.json();r=await app.inject({method:"POST",url:`/v1/regularidade/ppci/${ppci.id}/sistemas`,headers:headers("s1"),payload:{patrimonioUnidadeId:"SALA-1",tipo:"alarme",descricao:"Central",quantidade:1,dados:{}}});assert.equal(r.statusCode,201,r.body);let sistema=r.json();r=await app.inject({method:"PUT",url:`/v1/regularidade/ppci/${ppci.id}/sistemas/${sistema.id}`,headers:headers("",sistema.versao),payload:{patrimonioUnidadeId:"SALA-1",tipo:"alarme",descricao:"Central atualizada",quantidade:2,responsavel:"Engenheira de Segurança",dados:{}}});assert.equal(r.statusCode,200,r.body);sistema=r.json();r=await app.inject({method:"POST",url:`/v1/regularidade/ppci/${ppci.id}/inspecoes`,headers:headers("i1"),payload:{systemId:sistema.id,dataInspecao:"2026-08-24",tipo:"preventiva",resultado:"conforme",inspetor:"Equipe técnica",evidencias:[]}});assert.equal(r.statusCode,201,r.body);r=await app.inject({method:"DELETE",url:`/v1/regularidade/ppci/${ppci.id}/sistemas/${sistema.id}`,headers:headers("",sistema.versao),payload:{motivo:"Equipamento substituído"}});assert.equal(r.statusCode,200,r.body);assert.equal(r.json().modo,"inativado");r=await app.inject({method:"GET",url:`/v1/regularidade/ppci/${ppci.id}`,headers:headers()});assert.equal(r.json().sistemas.length,0);assert.equal(r.json().inspecoes.length,1);});

test("Sprint 31 cadastra medidor e preserva leituras ao remover",async(t)=>{const app=await criarApi();t.after(()=>app.close());let r=await app.inject({method:"POST",url:"/v1/utilidades/medidores",headers:headers("m1"),payload:{patrimonioUnidadeId:"PRE-1",codigo:"MED-001",nome:"Entrada geral",recurso:"energia",unidade:"kWh",direcao:"bidirecional",multiplicador:1,responsavel:"Engenheira de Segurança",dados:{}}});assert.equal(r.statusCode,201,r.body);let medidor=r.json();r=await app.inject({method:"POST",url:`/v1/utilidades/medidores/${medidor.id}/leituras`,headers:headers("l1"),payload:{dataLeitura:"2026-08-24T12:00:00.000Z",valor:1280.5,natureza:"leitura",origem:"manual",observacoes:"Leitura inicial"}});assert.equal(r.statusCode,201,r.body);r=await app.inject({method:"GET",url:`/v1/utilidades/medidores/${medidor.id}`,headers:headers()});assert.equal(r.statusCode,200);medidor=r.json();assert.equal(medidor.leituras.length,1);assert.equal(medidor.leituras[0].valor,1280.5);r=await app.inject({method:"DELETE",url:`/v1/utilidades/medidores/${medidor.id}`,headers:headers("",medidor.versao)});assert.equal(r.statusCode,200,r.body);assert.equal(r.json().modo,"inativado");});

test("responsáveis são limitados ao cliente ativo e incluem grupos",async(t)=>{const app=await criarApi();t.after(()=>app.close());const r=await app.inject({method:"GET",url:"/v1/responsaveis",headers:headers()});assert.equal(r.statusCode,200,r.body);assert.deepEqual(r.json().usuarios.map((x)=>x.nome),["Administrador local","Engenheira de Segurança"]);assert.equal(r.json().equipes.length,1);});

test("migração da Sprint 31 força RLS e imutabilidade das leituras",async()=>{const sql=await readFile(new URL("../server/migrations/039_operacao_ppci_utilidades_v31.sql",import.meta.url),"utf8");assert.match(sql,/CREATE TABLE app\.utility_meters/);assert.match(sql,/CREATE TABLE app\.utility_readings/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/utility_readings_imutaveis/);assert.match(sql,/ALTER TABLE app\.fire_safety_systems/);});

const apiUrl=process.env.PRUMO_DATABASE_URL||"",migrationUrl=process.env.PRUMO_MIGRATION_DATABASE_URL||"";
test("PostgreSQL isola medidores, leituras e responsáveis por equipe",{skip:!(apiUrl&&migrationUrl)&&"Conexões PostgreSQL de integração não configuradas."},async()=>{const sufixo=randomUUID().slice(0,8),tenantId=randomUUID(),teamA=randomUUID(),teamB=randomUUID(),subject=`teste-util-${sufixo}`;const admin=new Client({connectionString:migrationUrl}),repo=criarRepositorioPostgres({connectionString:apiUrl});const a={identity:{subject},tenantId,teamId:teamA},b={identity:{subject},tenantId,teamId:teamB};try{await admin.connect();await admin.query("INSERT INTO app.tenants(id,nome) VALUES($1,'Teste utilidades')",[tenantId]);await admin.query("INSERT INTO app.teams(tenant_id,id,nome) VALUES($1,$2,'Equipe A'),($1,$3,'Equipe B')",[tenantId,teamA,teamB]);await admin.query("INSERT INTO app.memberships(tenant_id,identity_subject,perfil_id) VALUES($1,$2,'administrador')",[tenantId,subject]);await admin.query("INSERT INTO app.team_memberships(tenant_id,team_id,identity_subject) VALUES($1,$2,$4),($1,$3,$4)",[tenantId,teamA,teamB,subject]);const cliente=await repo.criarUnidadePatrimonial(a,{nivel:"cliente",codigo:`C-${sufixo}`,nome:"Cliente"},`c-${sufixo}`);const site=await repo.criarUnidadePatrimonial(a,{nivel:"site",parentId:cliente.id,codigo:`S-${sufixo}`,nome:"Site"},`s-${sufixo}`);const medidor=await repo.criarMedidorUtilidade(a,{patrimonioUnidadeId:site.id,codigo:`MED-${sufixo}`,nome:"Entrada geral",recurso:"energia",unidade:"kWh",direcao:"bidirecional",dados:{}},`m-${sufixo}`);await repo.registrarLeituraUtilidade(a,medidor.id,{dataLeitura:"2026-08-24T12:00:00.000Z",valor:100,natureza:"leitura",origem:"manual"},`l-${sufixo}`);assert.equal((await repo.listarMedidoresUtilidades(a)).length,1);assert.equal((await repo.listarMedidoresUtilidades(b)).length,0);assert.equal((await repo.obterMedidorUtilidade(a,medidor.id)).leituras.length,1);const responsaveis=await repo.listarResponsaveisCorporativos(a);assert.equal(responsaveis.usuarios[0].id,subject);assert.equal(responsaveis.equipes.length,2);}finally{await repo.fechar();if(admin._connected){await admin.query("SELECT app.limpar_utilidades_tenant_teste($1)",[tenantId]);await admin.query("SELECT app.limpar_patrimonio_tenant_teste($1)",[tenantId]);await admin.query("BEGIN");await admin.query("SELECT app.ativar_contexto($1,$2,$3)",[tenantId,subject,teamA]);await admin.query("DELETE FROM app.domain_events");await admin.query("DELETE FROM app.idempotency_keys");await admin.query("COMMIT");await admin.query("SELECT app.limpar_auditoria_tenant_teste($1)",[tenantId]);await admin.query("DELETE FROM app.team_memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.memberships WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.teams WHERE tenant_id=$1",[tenantId]);await admin.query("DELETE FROM app.tenants WHERE id=$1",[tenantId]);await admin.end();}}});
