export const SIGIU_NAV_ITEMS = [
  { id: "visao-geral", moduleId: "visao-geral", label: "Visão Geral", icon: "⌂", grupo: "principal" },
  { id: "regularidade", moduleId: "regularidade", label: "Regularidade", icon: "✓", grupo: "principal" },
  { id: "hidrico", moduleId: "utilidades", label: "Utilidades", icon: "⚡", grupo: "infraestrutura" },
  { id: "patrimonio", moduleId: "patrimonio", label: "Patrimônio", icon: "▦", grupo: "infraestrutura" },
  { id: "planejamento", moduleId: "planejamento", label: "Solicitações", icon: "◇", grupo: "infraestrutura" },
  { id: "obras", moduleId: "obras", label: "Obras", icon: "⚒", grupo: "infraestrutura" },
  { id: "orcamento", moduleId: "orcamentos", label: "Orçamentos", icon: "▤", grupo: "infraestrutura" },
  { id: "suprimentos", moduleId: "suprimentos", label: "Suprimentos", icon: "◇", grupo: "gestao" },
  { id: "contratos", moduleId: "contratos", label: "Contratos", icon: "▤", grupo: "gestao" },
  { id: "financeiro", moduleId: "financeiro", label: "Financeiro", icon: "$", grupo: "gestao" },
  { id: "manutencao", moduleId: "manutencao", label: "Manutenção", icon: "🔧", grupo: "infraestrutura" },
  { id: "documentos", moduleId: "documentos", label: "Documentos", icon: "▣", grupo: "gestao" },
  { id: "convenios", moduleId: "convenios", label: "Convênios", icon: "⇄", grupo: "gestao" },
  { id: "relatorios", moduleId: "relatorios", label: "Relatórios", icon: "▥", grupo: "gestao" },
  { id: "administracao", moduleId: "administracao", label: "Administração", icon: "⚙", grupo: "gestao" },
];
