import { useEffect, useMemo, useState } from "react";
import { criarClientePrumo, obterConfiguracaoInfraestrutura, obterContextoDesenvolvimento } from "../services/infraestruturaCorporativa";

const STATUS={rascunho:"Rascunho",vigente:"Vigente",suspenso:"Suspenso",concluido:"Concluído",rescindido:"Rescindido",encerrado:"Encerrado",cancelado:"Cancelado"};
const ACOES={rascunho:[["ativar","Ativar"],["cancelar","Cancelar"]],vigente:[["suspender","Suspender"],["concluir","Concluir"],["rescindir","Rescindir"]],suspenso:[["reativar","Reativar"],["rescindir","Rescindir"]],concluido:[["encerrar","Encerrar"]],rescindido:[["encerrar","Encerrar"]]};
const hoje=()=>new Date().toISOString().slice(0,10);
const chave=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const moeda=(valor)=>Number(valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const proximoCodigo=(itens)=>`CT-${String(itens.reduce((m,x)=>Math.max(m,Number(String(x.codigo||"").match(/(\d+)$/)?.[1])||0),0)+1).padStart(3,"0")}`;
const vazio={processId:"",supplierId:"",codigo:"",numero:"",titulo:"",objeto:"",tipoInstrumento:"contrato",regime:"publico",dataAssinatura:hoje(),dataInicio:hoje(),dataFim:`${new Date().getFullYear()+1}-${hoje().slice(5)}`,valorInicial:0,dados:{}};

export default function Contratos(){
  const cliente=useMemo(()=>{const config=obterConfiguracaoInfraestrutura();return config.apiConfigurada?criarClientePrumo({baseUrl:config.apiUrl,obterContexto:()=>obterContextoDesenvolvimento()}):null;},[]);
  const [dados,setDados]=useState({contratos:[],processos:[],fornecedores:[]}); const [aba,setAba]=useState("contratos"); const [filtro,setFiltro]=useState(""); const [selecionado,setSelecionado]=useState(null); const [modal,setModal]=useState(null); const [form,setForm]=useState(vazio); const [mensagem,setMensagem]=useState(""); const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false);
  async function carregar(){if(!cliente){setMensagem("Configure a API local para utilizar Contratos.");setCarregando(false);return;}try{const [contratos,processos,fornecedores]=await Promise.all([cliente.listarContratos(),cliente.listarProcessosContratacao(),cliente.listarFornecedores()]);setDados({contratos,processos:processos.filter(x=>["aprovada","pedido_emitido","concluida"].includes(x.status)),fornecedores});setMensagem("");}catch(e){setMensagem(e.message);}finally{setCarregando(false);}}
  useEffect(()=>{carregar();},[]);
  const lista=useMemo(()=>dados.contratos.filter(x=>{const texto=`${x.codigo} ${x.numero} ${x.titulo} ${x.objeto}`.toLocaleLowerCase("pt-BR");const ok=!filtro||texto.includes(filtro.toLocaleLowerCase("pt-BR"));if(!ok)return false;if(aba==="vigencias")return !["encerrado","cancelado"].includes(x.status)&&x.dataFim<=new Date(Date.now()+90*86400000).toISOString().slice(0,10);if(aba==="encerrados")return ["encerrado","cancelado"].includes(x.status);return true;}),[dados.contratos,filtro,aba]);
  const indicadores=useMemo(()=>({total:dados.contratos.length,vigentes:dados.contratos.filter(x=>x.status==="vigente").length,vencer:dados.contratos.filter(x=>x.status==="vigente"&&x.dataFim<=new Date(Date.now()+90*86400000).toISOString().slice(0,10)).length,saldo:dados.contratos.filter(x=>["vigente","suspenso"].includes(x.status)).reduce((s,x)=>s+Number(x.saldo||0),0)}),[dados.contratos]);
  async function abrir(item){try{setSelecionado(await cliente.obterContrato(item.id));}catch(e){setMensagem(e.message);}}
  function novo(item=null){setForm(item?{...item,dados:item.dados||{}}:{...vazio,dados:{},codigo:proximoCodigo(dados.contratos),numero:`${String(dados.contratos.length+1).padStart(3,"0")}/${new Date().getFullYear()}`});setModal("contrato");}
  async function atualizarDetalhe(id=selecionado?.id){if(id)setSelecionado(await cliente.obterContrato(id));await carregar();}
  async function salvarContrato(evento){evento.preventDefault();setSalvando(true);const fd=Object.fromEntries(new FormData(evento.currentTarget));const payload={...fd,valorInicial:Number(fd.valorInicial),dados:form.dados||{}};try{if(form.id)await cliente.atualizarContrato(form.id,payload,form.versao);else await cliente.criarContrato(payload,chave());setModal(null);await atualizarDetalhe(form.id);}catch(e){setMensagem(e.message);}finally{setSalvando(false);}}
  async function decidir(acao){const exige=["suspender","rescindir","cancelar","encerrar"].includes(acao);const justificativa=exige?globalThis.prompt("Informe a justificativa da decisão:"):"";if(justificativa===null)return;try{const r=await cliente.decidirContrato(selecionado.id,{acao,justificativa,dados:{}},selecionado.versao,chave());await atualizarDetalhe(r.contrato.id);}catch(e){setMensagem(e.message);}}
  async function salvarOperacao(evento){evento.preventDefault();setSalvando(true);const fd=Object.fromEntries(new FormData(evento.currentTarget));try{if(modal==="responsavel")await cliente.adicionarResponsavelContrato(selecionado.id,fd,chave());if(modal==="aditivo")await cliente.registrarAditivoContrato(selecionado.id,{...fd,valor:Number(fd.valor||0),dados:{}},selecionado.versao,chave());if(modal==="garantia")await cliente.registrarGarantiaContrato(selecionado.id,{...fd,valor:Number(fd.valor||0),dados:{}},chave());if(modal==="ocorrencia")await cliente.registrarOcorrenciaContrato(selecionado.id,fd,chave());if(modal==="sancao")await cliente.aplicarSancaoContrato(selecionado.id,{...fd,valor:Number(fd.valor||0)},chave());if(modal==="execucao")await cliente.registrarExecucaoContrato(selecionado.id,{...fd,valor:Number(fd.valor)},chave());setModal(null);await atualizarDetalhe();}catch(e){setMensagem(e.message);}finally{setSalvando(false);}}
  return <div className="sigiu-page sigiu-contracts">
    <header className="sigiu-page-heading sigiu-page-heading--modulo"><div><span className="sigiu-page-eyebrow">SPRINT 14 · GESTÃO CONTRATUAL</span><h1>Contratos e atas</h1><p>Instrumentos, vigência, saldos, fiscalização, alterações, garantias e encerramento.</p></div><button className="sigiu-primary" onClick={()=>novo()}>+ Novo contrato</button></header>
    {mensagem&&<div className="sigiu-feedback">{mensagem}</div>}
    <section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>Instrumentos</small><strong>{indicadores.total}</strong></article><article className="sigiu-module-kpi"><small>Vigentes</small><strong>{indicadores.vigentes}</strong></article><article className="sigiu-module-kpi"><small>Vencem em 90 dias</small><strong>{indicadores.vencer}</strong></article><article className="sigiu-module-kpi"><small>Saldo contratual</small><strong>{moeda(indicadores.saldo)}</strong></article></section>
    <nav className="sigiu-tabs"><button className={`sigiu-tab ${aba==="contratos"?"is-active":""}`} onClick={()=>setAba("contratos")}>Todos</button><button className={`sigiu-tab ${aba==="vigencias"?"is-active":""}`} onClick={()=>setAba("vigencias")}>Vigências críticas</button><button className={`sigiu-tab ${aba==="encerrados"?"is-active":""}`} onClick={()=>setAba("encerrados")}>Encerrados</button></nav>
    <div className="sigiu-planning-toolbar"><input aria-label="Pesquisar contratos" placeholder="Pesquisar código, número, título ou objeto" value={filtro} onChange={e=>setFiltro(e.target.value)}/></div>
    {carregando?<div className="sigiu-empty">Carregando contratos…</div>:<div className="sigiu-planning-table"><table><thead><tr><th>Contrato</th><th>Instrumento</th><th>Vigência</th><th>Valor atual</th><th>Executado</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody>{lista.map(x=><tr key={x.id} onClick={()=>abrir(x)}><td><b>{x.codigo}</b><span>{x.titulo}</span></td><td>{x.numero}<br/><small>{String(x.tipoInstrumento).replaceAll("_"," ")}</small></td><td>{x.dataInicio}<br/><b>{x.dataFim}</b></td><td>{moeda(x.valorAtual)}</td><td>{moeda(x.valorExecutado)}</td><td><b>{moeda(x.saldo)}</b></td><td><span className={`sigiu-status status-${x.status}`}>{STATUS[x.status]}</span></td><td><button className="sigiu-link">Abrir</button></td></tr>)}</tbody></table>{!lista.length&&<div className="sigiu-empty">Nenhum contrato encontrado.</div>}</div>}
    {selecionado&&<div className="sigiu-drawer-backdrop" onClick={()=>setSelecionado(null)}><aside className="sigiu-planning-drawer sigiu-contract-drawer" onClick={e=>e.stopPropagation()}><header><div><span className="sigiu-page-eyebrow">{selecionado.numero} · {STATUS[selecionado.status]}</span><h2>{selecionado.titulo}</h2><p>{selecionado.objeto}</p></div><button aria-label="Fechar" onClick={()=>setSelecionado(null)}>×</button></header>
      <section className="sigiu-contract-summary"><article><span>Valor atual</span><strong>{moeda(selecionado.valorAtual)}</strong></article><article><span>Executado</span><strong>{moeda(selecionado.valorExecutado)}</strong></article><article><span>Saldo</span><strong>{moeda(selecionado.saldo)}</strong></article><article><span>Vigência</span><strong>{selecionado.dataFim}</strong></article></section>
      <div className="sigiu-detail-actions">{selecionado.status==="rascunho"&&<><button onClick={()=>novo(selecionado)}>Editar</button><button onClick={()=>setModal("responsavel")}>Designar responsável</button></>}{selecionado.status==="vigente"&&<><button onClick={()=>setModal("execucao")}>Registrar execução</button><button onClick={()=>setModal("aditivo")}>Aditivo</button><button onClick={()=>setModal("garantia")}>Garantia</button><button onClick={()=>setModal("ocorrencia")}>Ocorrência</button><button onClick={()=>setModal("sancao")}>Sanção</button></>}{selecionado.status==="suspenso"&&<><button onClick={()=>setModal("aditivo")}>Aditivo</button><button onClick={()=>setModal("ocorrencia")}>Ocorrência</button></>}{(ACOES[selecionado.status]||[]).map(([id,label])=><button key={id} className={id==="rescindir"||id==="cancelar"?"danger":""} onClick={()=>decidir(id)}>{label}</button>)}</div>
      <section className="sigiu-contract-detail-grid"><div><h3>Gestão e fiscalização</h3>{selecionado.responsaveis.map(x=><article key={x.id}><b>{x.nome}</b><span>{x.papel.replaceAll("_"," ")} · {x.atoDesignacao||"sem ato informado"}</span></article>)}{!selecionado.responsaveis.length&&<p>Nenhum responsável designado.</p>}</div><div><h3>Aditivos e garantias</h3>{selecionado.aditivos.map(x=><article key={x.id}><b>{x.numero} · {x.tipo}</b><span>{moeda(x.valor)} {x.novaDataFim&&`· até ${x.novaDataFim}`}</span></article>)}{selecionado.garantias.map(x=><article key={x.id}><b>{x.tipo.replaceAll("_"," ")}</b><span>{moeda(x.valor)} · {x.status}</span></article>)}</div><div><h3>Execução</h3>{selecionado.execucoes.map(x=><article key={x.id}><b>{moeda(x.valor)}</b><span>{x.dataExecucao} · {x.origem}</span></article>)}</div><div><h3>Ocorrências e sanções</h3>{selecionado.ocorrencias.map(x=><article key={x.id}><b>{x.severidade} · {x.tipo}</b><span>{x.descricao}</span></article>)}{selecionado.sancoes.map(x=><article key={x.id}><b>Sanção: {x.tipo}</b><span>{x.fundamento} · {moeda(x.valor)}</span></article>)}</div></section>
      <section className="sigiu-timeline"><h3>Histórico decisório</h3>{selecionado.decisoes.map(x=><article key={x.id}><i/><div><b>{x.acao.replaceAll("_"," ")}</b><span>{new Date(x.decididoEm).toLocaleString("pt-BR")}</span><p>{x.justificativa||`${x.statusAnterior} → ${x.statusNovo}`}</p></div></article>)}</section>
    </aside></div>}
    {modal==="contrato"&&<div className="sigiu-modal-backdrop"><form className="sigiu-modal" onSubmit={salvarContrato}><header><div><span className="sigiu-page-eyebrow">Instrumento contratual</span><h2>{form.id?"Editar contrato":"Novo contrato"}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></header><div className="sigiu-form-grid"><label>Processo<select name="processId" required defaultValue={form.processId}><option value="">Selecione</option>{dados.processos.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.titulo}</option>)}</select></label><label>Fornecedor contratado<select name="supplierId" required defaultValue={form.supplierId}><option value="">Selecione o vencedor</option>{dados.fornecedores.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.razaoSocial}</option>)}</select></label><label>Código<input name="codigo" required defaultValue={form.codigo}/></label><label>Número<input name="numero" required defaultValue={form.numero}/></label><label>Instrumento<select name="tipoInstrumento" defaultValue={form.tipoInstrumento}><option value="contrato">Contrato</option><option value="ata_registro_precos">Ata de registro de preços</option><option value="ordem_servico">Ordem de serviço</option><option value="termo">Termo</option><option value="instrumento_equivalente">Instrumento equivalente</option></select></label><label>Regime<select name="regime" defaultValue={form.regime}><option value="publico">Público</option><option value="federacao">Federação</option><option value="privado">Privado</option></select></label><label className="span-2">Título<input name="titulo" required defaultValue={form.titulo}/></label><label>Valor inicial<input name="valorInicial" type="number" min="0.01" step="0.01" required defaultValue={form.valorInicial}/></label><label>Assinatura<input name="dataAssinatura" type="date" defaultValue={form.dataAssinatura}/></label><label>Início<input name="dataInicio" type="date" required defaultValue={form.dataInicio}/></label><label>Fim<input name="dataFim" type="date" required defaultValue={form.dataFim}/></label><label className="span-2">Objeto<textarea name="objeto" required defaultValue={form.objeto}/></label></div><footer><button type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando?"Salvando…":"Salvar"}</button></footer></form></div>}
    {modal&&modal!=="contrato"&&<div className="sigiu-modal-backdrop"><form className="sigiu-modal sigiu-planning-small" onSubmit={salvarOperacao}><header><div><span className="sigiu-page-eyebrow">Gestão contratual</span><h2>{{responsavel:"Designar responsável",aditivo:"Registrar aditivo",garantia:"Registrar garantia",ocorrencia:"Registrar ocorrência",sancao:"Aplicar sanção",execucao:"Registrar execução"}[modal]}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></header><div className="sigiu-form-grid">
      {modal==="responsavel"&&<><label>Papel<select name="papel"><option value="gestor">Gestor</option><option value="fiscal_tecnico">Fiscal técnico</option><option value="fiscal_administrativo">Fiscal administrativo</option><option value="substituto">Substituto</option></select></label><label className="span-2">Nome<input name="nome" required/></label><label>Início<input name="dataInicio" type="date" required defaultValue={hoje()}/></label><label>Ato de designação<input name="atoDesignacao"/></label><label>E-mail<input name="email" type="email"/></label></>}
      {modal==="aditivo"&&<><label>Número<input name="numero" required defaultValue={`TA-${String(selecionado.aditivos.length+1).padStart(2,"0")}`}/></label><label>Tipo<select name="tipo"><option value="prazo">Prazo</option><option value="valor">Acréscimo de valor</option><option value="prazo_valor">Prazo e valor</option><option value="supressao">Supressão</option><option value="reajuste">Reajuste</option></select></label><label>Valor<input name="valor" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Nova data final<input name="novaDataFim" type="date" defaultValue={selecionado.dataFim}/></label><label className="span-2">Justificativa<textarea name="justificativa" required/></label></>}
      {modal==="garantia"&&<><label>Tipo<select name="tipo"><option value="seguro_garantia">Seguro-garantia</option><option value="caucao">Caução</option><option value="fianca_bancaria">Fiança bancária</option><option value="retencao">Retenção</option><option value="dispensada">Dispensada</option></select></label><label>Número<input name="numero"/></label><label>Instituição<input name="instituicao"/></label><label>Valor<input name="valor" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Início<input name="dataInicio" type="date"/></label><label>Fim<input name="dataFim" type="date"/></label></>}
      {modal==="ocorrencia"&&<><label>Data<input name="dataOcorrencia" type="date" defaultValue={hoje()}/></label><label>Tipo<input name="tipo" defaultValue="registro"/></label><label>Severidade<select name="severidade"><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></label><label className="span-2">Descrição<textarea name="descricao" required/></label><label className="span-2">Providência<textarea name="providencia"/></label></>}
      {modal==="sancao"&&<><label>Tipo<select name="tipo"><option value="advertencia">Advertência</option><option value="multa">Multa</option><option value="suspensao">Suspensão</option><option value="impedimento">Impedimento</option><option value="declaracao_inidoneidade">Declaração de inidoneidade</option></select></label><label>Ocorrência<select name="occurrenceId"><option value="">Sem vínculo</option>{selecionado.ocorrencias.map(x=><option key={x.id} value={x.id}>{x.dataOcorrencia} · {x.descricao.slice(0,40)}</option>)}</select></label><label>Valor<input name="valor" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Data<input name="dataAplicacao" type="date" defaultValue={hoje()}/></label><label className="span-2">Fundamento<textarea name="fundamento" required/></label></>}
      {modal==="execucao"&&<><label>Origem<select name="origem"><option value="manual">Registro manual</option><option value="medicao">Medição</option><option value="recebimento">Recebimento</option><option value="financeiro">Financeiro</option></select></label><label>Referência<input name="referenciaId"/></label><label>Data<input name="dataExecucao" type="date" defaultValue={hoje()}/></label><label>Valor<input name="valor" type="number" min="0.01" max={selecionado.saldo} step="0.01" required/></label><label className="span-2">Descrição<textarea name="descricao"/></label></>}
    </div><footer><button type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando?"Salvando…":"Confirmar"}</button></footer></form></div>}
  </div>;
}
