import { useEffect,useMemo,useState } from "react";
import { criarClientePrumo,obterConfiguracaoInfraestrutura,obterContextoDesenvolvimento } from "../services/infraestruturaCorporativa";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const chave=()=>crypto.randomUUID(); const hoje=()=>new Date().toISOString().slice(0,10);
const titulo=v=>String(v||"").replaceAll("_"," ").replace(/^./,x=>x.toUpperCase());
const proximo=itens=>`CV-${String(itens.reduce((m,x)=>Math.max(m,Number(String(x.codigo).match(/(\d+)$/)?.[1])||0),0)+1).padStart(3,"0")}`;

export default function Convenios(){
 const cliente=useMemo(()=>{const c=obterConfiguracaoInfraestrutura();return c.apiConfigurada?criarClientePrumo({baseUrl:c.apiUrl,obterContexto:()=>obterContextoDesenvolvimento()}):null;},[]);
 const [itens,setItens]=useState([]),[resumo,setResumo]=useState({}),[selecionado,setSelecionado]=useState(null),[modal,setModal]=useState(""),[mensagem,setMensagem]=useState(""),[salvando,setSalvando]=useState(false),[filtro,setFiltro]=useState("");
 async function carregar(){if(!cliente)return;try{const [lista,kpis]=await Promise.all([cliente.listarConvenios(),cliente.obterResumoConvenios()]);setItens(lista);setResumo(kpis);setMensagem("");}catch(e){setMensagem(e.message);}}
 useEffect(()=>{carregar();},[]);
 async function abrir(id){try{setSelecionado(await cliente.obterConvenio(id));}catch(e){setMensagem(e.message);}}
 async function recarregar(id=selecionado?.id){await carregar();if(id)setSelecionado(await cliente.obterConvenio(id));}
 async function salvar(e){e.preventDefault();setSalvando(true);const f=Object.fromEntries(new FormData(e.currentTarget));try{
  if(modal==="convenio")await cliente.criarConvenio({...f,valorRepasse:Number(f.valorRepasse||0),valorContrapartida:Number(f.valorContrapartida||0),dados:{}},chave());
  if(modal==="meta")await cliente.adicionarMetaConvenio(selecionado.id,{...f,quantidadePrevista:Number(f.quantidadePrevista||0),valorPrevisto:Number(f.valorPrevisto||0),dados:{}},chave());
  if(modal==="repasse")await cliente.registrarRepasseConvenio(selecionado.id,{...f,valor:Number(f.valor),dados:{}},chave());
  if(modal==="execucao")await cliente.registrarExecucaoConvenio(selecionado.id,{...f,quantidadeExecutada:Number(f.quantidadeExecutada||0),valorExecutado:Number(f.valorExecutado||0),dados:{}},chave());
  if(modal==="prestacao")await cliente.criarPrestacaoConvenio(selecionado.id,{...f,valorInformado:Number(f.valorInformado||0),dados:{}},chave());
  if(modal==="diligencia")await cliente.criarDiligenciaConvenio(selecionado.id,{...f,dados:{}},chave());
  setModal("");await recarregar(modal==="convenio"?undefined:selecionado?.id);
 }catch(err){setMensagem(err.message);}finally{setSalvando(false);}}
 async function decidir(acao){try{const x=await cliente.decidirConvenio(selecionado.id,{acao,justificativa:"Decisão registrada na gestão do instrumento."},selecionado.versao,chave());await recarregar(x.id);}catch(e){setMensagem(e.message);}}
 const filtrados=itens.filter(x=>!filtro||`${x.codigo} ${x.titulo} ${x.concedente} ${x.convenente}`.toLowerCase().includes(filtro.toLowerCase()));
 const acoes={rascunho:[["ativar","Ativar"],["cancelar","Cancelar"]],vigente:[["iniciar_execucao","Iniciar execução"]],em_execucao:[["prestar_contas","Prestar contas"]],prestacao_contas:[["encerrar","Encerrar"],["reabrir_execucao","Reabrir execução"]]}[selecionado?.status]||[];
 return <div className="sigiu-page sigiu-convenios"><header className="sigiu-page-heading sigiu-page-heading--modulo"><div><span className="sigiu-page-eyebrow">Transferências e parcerias</span><h1>Convênios e prestação de contas</h1><p>Instrumentos, metas, repasses, execução físico-financeira, diligências e prestação de contas.</p></div><button className="sigiu-primary" onClick={()=>setModal("convenio")}>+ Novo convênio</button></header>
 {mensagem&&<div className="sigiu-feedback">{mensagem}</div>}
 <section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>Instrumentos</small><strong>{resumo.total||0}</strong><em>{resumo.vigentes||0} vigentes</em></article><article className="sigiu-module-kpi"><small>Valor conveniado</small><strong>{moeda(resumo.valorTotal)}</strong></article><article className="sigiu-module-kpi"><small>Executado</small><strong>{moeda(resumo.executado)}</strong></article><article className="sigiu-module-kpi"><small>Diligências abertas</small><strong>{resumo.diligenciasAbertas||0}</strong></article></section>
 <div className="sigiu-planning-toolbar"><input aria-label="Pesquisar convênios" placeholder="Pesquisar código, instrumento ou partícipe" value={filtro} onChange={e=>setFiltro(e.target.value)}/></div>
 <div className="sigiu-planning-table"><table><thead><tr><th>Instrumento</th><th>Concedente / convenente</th><th>Vigência</th><th>Valor</th><th>Execução</th><th>Status</th><th></th></tr></thead><tbody>{filtrados.map(x=><tr key={x.id} onClick={()=>abrir(x.id)}><td><b>{x.codigo}</b><span>{x.titulo}</span></td><td>{x.concedente}<br/><small>{x.convenente}</small></td><td>{x.dataInicio} a {x.dataFim}</td><td>{moeda(x.resumo?.valorTotal)}</td><td>{moeda(x.resumo?.executado)}</td><td><span className={`sigiu-status status-${x.status}`}>{titulo(x.status)}</span></td><td><button className="sigiu-link">Abrir</button></td></tr>)}</tbody></table>{!filtrados.length&&<div className="sigiu-empty">Nenhum convênio cadastrado.</div>}</div>
 {selecionado&&<div className="sigiu-drawer-backdrop" onClick={()=>setSelecionado(null)}><aside className="sigiu-planning-drawer sigiu-contract-drawer" onClick={e=>e.stopPropagation()}><header><div><span className="sigiu-page-eyebrow">{selecionado.codigo} · {titulo(selecionado.status)}</span><h2>{selecionado.titulo}</h2><p>{selecionado.objeto}</p></div><button onClick={()=>setSelecionado(null)}>×</button></header><section className="sigiu-contract-summary"><article><span>Valor total</span><strong>{moeda(selecionado.resumo.valorTotal)}</strong></article><article><span>Recebido</span><strong>{moeda(selecionado.resumo.recebido)}</strong></article><article><span>Executado</span><strong>{moeda(selecionado.resumo.executado)}</strong></article><article><span>Saldo</span><strong>{moeda(selecionado.resumo.saldoExecutar)}</strong></article></section><div className="sigiu-detail-actions">{acoes.map(([id,label])=><button key={id} onClick={()=>decidir(id)}>{label}</button>)}<button onClick={()=>setModal("meta")}>+ Meta</button><button onClick={()=>setModal("repasse")}>+ Repasse</button><button onClick={()=>setModal("execucao")}>+ Execução</button><button onClick={()=>setModal("prestacao")}>+ Prestação</button><button onClick={()=>setModal("diligencia")}>+ Diligência</button></div>
 <section className="sigiu-timeline"><h3>Metas e execução</h3>{selecionado.metas.map(x=><article key={x.id}><i/><div><b>{x.codigo} · {x.descricao}</b><span>{x.status} · {x.quantidadePrevista} {x.unidade} · {moeda(x.valorPrevisto)}</span></div></article>)}{selecionado.execucoes.map(x=><article key={x.id}><i/><div><b>Execução · {moeda(x.valorExecutado)}</b><span>{x.dataExecucao} · {x.descricao}</span></div></article>)}</section><section className="sigiu-timeline"><h3>Prestação de contas e diligências</h3>{selecionado.prestacoes.map(x=><article key={x.id}><i/><div><b>{titulo(x.tipo)} · {titulo(x.status)}</b><span>{x.periodoInicio} a {x.periodoFim} · {moeda(x.valorInformado)}</span></div></article>)}{selecionado.diligencias.map(x=><article key={x.id}><i/><div><b>{x.titulo} · {titulo(x.status)}</b><span>Prazo {x.prazo}</span><p>{x.descricao}</p></div></article>)}</section></aside></div>}
 {modal&&<div className="sigiu-modal-backdrop"><form className="sigiu-modal sigiu-planning-small" onSubmit={salvar}><header><div><span className="sigiu-page-eyebrow">Convênios</span><h2>{{convenio:"Novo convênio",meta:"Nova meta",repasse:"Novo repasse",execucao:"Registrar execução",prestacao:"Nova prestação de contas",diligencia:"Nova diligência"}[modal]}</h2></div><button type="button" onClick={()=>setModal("")}>×</button></header><div className="sigiu-form-grid">
 {modal==="convenio"&&<><label>Código<input name="codigo" required defaultValue={proximo(itens)}/></label><label>Número<input name="numero"/></label><label>Programa<input name="programa"/></label><label className="span-2">Título<input name="titulo" required/></label><label>Concedente<input name="concedente" required/></label><label>Convenente<input name="convenente" required/></label><label>Início<input name="dataInicio" type="date" required defaultValue={hoje()}/></label><label>Fim<input name="dataFim" type="date" required/></label><label>Repasse<input name="valorRepasse" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Contrapartida<input name="valorContrapartida" type="number" min="0" step="0.01" defaultValue="0"/></label><label className="span-2">Objeto<textarea name="objeto" required/></label></>}
 {modal==="meta"&&<><label>Código<input name="codigo" required defaultValue={`M-${String(selecionado.metas.length+1).padStart(2,"0")}`}/></label><label className="span-2">Descrição<input name="descricao" required/></label><label>Unidade<input name="unidade"/></label><label>Quantidade<input name="quantidadePrevista" type="number" min="0" step="0.0001"/></label><label>Valor<input name="valorPrevisto" type="number" min="0" step="0.01"/></label><label>Início<input name="inicioPrevisto" type="date"/></label><label>Fim<input name="fimPrevisto" type="date"/></label></>}
 {modal==="repasse"&&<><label>Tipo<select name="tipo"><option value="repasse">Repasse</option><option value="contrapartida">Contrapartida</option><option value="rendimento">Rendimento</option><option value="devolucao">Devolução</option></select></label><label>Parcela<input name="parcela"/></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required/></label><label>Previsto<input name="dataPrevista" type="date"/></label><label>Realizado<input name="dataRealizada" type="date"/></label><label>Status<select name="status"><option value="previsto">Previsto</option><option value="recebido">Recebido</option><option value="devolvido">Devolvido</option></select></label><label className="span-2">Referência<input name="referencia"/></label></>}
 {modal==="execucao"&&<><label>Meta<select name="goalId"><option value="">Execução geral</option>{selecionado.metas.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.descricao}</option>)}</select></label><label>Data<input name="dataExecucao" type="date" required defaultValue={hoje()}/></label><label>Quantidade<input name="quantidadeExecutada" type="number" min="0" step="0.0001"/></label><label>Valor<input name="valorExecutado" type="number" min="0" max={selecionado.resumo.saldoExecutar} step="0.01"/></label><label className="span-2">Descrição<textarea name="descricao" required/></label><label className="span-2">Referência/evidência<input name="referencia"/></label></>}
 {modal==="prestacao"&&<><label>Tipo<select name="tipo"><option value="parcial">Parcial</option><option value="final">Final</option></select></label><label>Início<input name="periodoInicio" type="date" required/></label><label>Fim<input name="periodoFim" type="date" required/></label><label>Valor informado<input name="valorInformado" type="number" min="0" step="0.01"/></label><label className="span-2">Protocolo<input name="protocolo"/></label></>}
 {modal==="diligencia"&&<><label className="span-2">Título<input name="titulo" required/></label><label>Prazo<input name="prazo" type="date" required/></label><label className="span-2">Descrição<textarea name="descricao" required/></label></>}
 </div><footer><button type="button" onClick={()=>setModal("")}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando?"Salvando…":"Confirmar"}</button></footer></form></div>}</div>;
}
