import { useEffect, useMemo, useState } from "react";
import { criarClientePrumo, obterConfiguracaoInfraestrutura, obterContextoDesenvolvimento } from "../services/infraestruturaCorporativa";

const hoje=()=>new Date().toISOString().slice(0,10);
const chave=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const moeda=(valor)=>Number(valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const titulo=(valor)=>String(valor||"").replaceAll("_"," ").replace(/^./,letra=>letra.toUpperCase());
const STATUS={rascunho:"Rascunho",reservado:"Reservado",comprometido:"Comprometido",parcialmente_liquidado:"Parcialmente liquidado",liquidado:"Liquidado",parcialmente_pago:"Parcialmente pago",pago:"Pago",cancelado:"Cancelado"};
const proximo=(prefixo,itens)=>`${prefixo}-${String(itens.reduce((maior,item)=>Math.max(maior,Number(String(item.codigo||"").match(/(\d+)$/)?.[1])||0),0)+1).padStart(3,"0")}`;

export default function Financeiro(){
  const cliente=useMemo(()=>{const config=obterConfiguracaoInfraestrutura();return config.apiConfigurada?criarClientePrumo({baseUrl:config.apiUrl,obterContexto:()=>obterContextoDesenvolvimento()}):null;},[]);
  const [dados,setDados]=useState({centros:[],fontes:[],orcamentos:[],compromissos:[],contratos:[],pedidos:[],resumo:null});
  const [aba,setAba]=useState("compromissos"); const [ano,setAno]=useState(new Date().getFullYear()); const [filtro,setFiltro]=useState(""); const [selecionado,setSelecionado]=useState(null); const [movimentoSelecionado,setMovimentoSelecionado]=useState(null); const [modal,setModal]=useState(null); const [operacao,setOperacao]=useState(""); const [mensagem,setMensagem]=useState(""); const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false);
  async function carregar(){if(!cliente){setMensagem("Configure a API local para utilizar o Financeiro.");setCarregando(false);return;}try{const [centros,fontes,orcamentos,compromissos,contratos,pedidos,resumo]=await Promise.all([cliente.listarCentrosCustoFinanceiros(),cliente.listarFontesFinanceiras(),cliente.listarOrcamentosFinanceiros({ano}),cliente.listarCompromissosFinanceiros(),cliente.listarContratos(),cliente.listarPedidosCompra(),cliente.obterResumoFinanceiro({ano})]);setDados({centros,fontes,orcamentos,compromissos,contratos,pedidos,resumo});setMensagem("");}catch(e){setMensagem(e.message);}finally{setCarregando(false);}}
  useEffect(()=>{carregar();},[ano]);
  const termos=dados.resumo?.terminologia||{orçamento:"Orçamento",reserva:"Reserva",compromisso:"Compromisso",liquidacao:"Liquidação",pagamento:"Pagamento"};
  const compromissos=useMemo(()=>dados.compromissos.filter(item=>!filtro||`${item.codigo} ${item.descricao} ${item.beneficiario}`.toLocaleLowerCase("pt-BR").includes(filtro.toLocaleLowerCase("pt-BR"))),[dados.compromissos,filtro]);
  const orcamentoPorId=useMemo(()=>new Map(dados.orcamentos.map(item=>[item.id,item])),[dados.orcamentos]);
  const origens=useMemo(()=>[...dados.contratos.map(item=>({id:item.id,tipo:"contrato",label:`Contrato ${item.numero} · ${item.titulo}`})),...dados.pedidos.map(item=>({id:item.id,tipo:"pedido",label:`Pedido ${item.codigo} · ${moeda(item.valorTotal)}`}))],[dados.contratos,dados.pedidos]);
  async function abrir(item){try{setSelecionado(await cliente.obterCompromissoFinanceiro(item.id));}catch(e){setMensagem(e.message);}}
  async function recarregarDetalhe(id=selecionado?.id){await carregar();if(id)setSelecionado(await cliente.obterCompromissoFinanceiro(id));}
  function abrirOperacao(tipo){setOperacao(tipo);setModal("movimento");}
  async function salvar(evento){evento.preventDefault();setSalvando(true);const fd=Object.fromEntries(new FormData(evento.currentTarget));try{
    if(modal==="centro")await cliente.criarCentroCustoFinanceiro({...fd,dados:{}},chave());
    if(modal==="fonte")await cliente.criarFonteFinanceira({...fd,dados:{}},chave());
    if(modal==="orcamento")await cliente.criarOrcamentoFinanceiro({...fd,ano:Number(fd.ano),valorInicial:Number(fd.valorInicial),ajustes:Number(fd.ajustes||0),dados:{}},chave());
    if(modal==="compromisso"){const origem=origens.find(item=>item.id===fd.origemId);await cliente.criarCompromissoFinanceiro({...fd,origemTipo:origem?.tipo||fd.origemTipo||"manual",valorTotal:Number(fd.valorTotal),dados:{}},chave());}
    if(modal==="movimento"){const payload={...fd,tipo:operacao,valor:Number(fd.valor||0),retencoes:Number(fd.retencoes||0),glosas:Number(fd.glosas||0),dados:{}};const resultado=await cliente.registrarMovimentoFinanceiro(selecionado.id,payload,selecionado.versao,chave());setSelecionado(await cliente.obterCompromissoFinanceiro(resultado.compromisso.id));}
    if(modal==="conciliacao"){await cliente.conciliarMovimentoFinanceiro(movimentoSelecionado.id,{...fd,diferenca:Number(fd.diferenca||0)},chave());setSelecionado(await cliente.obterCompromissoFinanceiro(selecionado.id));}
    setModal(null);setMovimentoSelecionado(null);await recarregarDetalhe(modal==="movimento"||modal==="conciliacao"?selecionado?.id:undefined);
  }catch(e){setMensagem(e.message);}finally{setSalvando(false);}}
  const acoes=selecionado?[
    ...(["rascunho"].includes(selecionado.status)?[["reserva",termos.reserva],["compromisso",termos.compromisso],["cancelamento","Cancelar"]]:[]),
    ...(["reservado"].includes(selecionado.status)?[["compromisso",termos.compromisso],["cancelamento","Cancelar"]]:[]),
    ...(["comprometido","parcialmente_liquidado","parcialmente_pago"].includes(selecionado.status)&&selecionado.resumo.saldoCompromisso>0?[["liquidacao",termos.liquidacao]]:[]),
    ...(["liquidado","parcialmente_liquidado","parcialmente_pago"].includes(selecionado.status)&&selecionado.resumo.saldoAPagar>0?[["pagamento",termos.pagamento]]:[]),
  ]:[];
  return <div className="sigiu-page sigiu-financeiro">
    <header className="sigiu-page-heading sigiu-page-heading--modulo"><div><span className="sigiu-page-eyebrow">Gestão financeira</span><h1>Financeiro-orçamentário</h1><p>Planejamento, fontes, compromissos, retenções, glosas, pagamentos e conciliação.</p></div><button className="sigiu-primary" onClick={()=>setModal("compromisso")}>+ Novo compromisso</button></header>
    {mensagem&&<div className="sigiu-feedback">{mensagem}</div>}
    <section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>{termos.orçamento} {ano}</small><strong>{moeda(dados.resumo?.previsto)}</strong></article><article className="sigiu-module-kpi"><small>{termos.compromisso}</small><strong>{moeda(dados.resumo?.comprometido)}</strong></article><article className="sigiu-module-kpi"><small>{termos.liquidacao}</small><strong>{moeda(dados.resumo?.liquidado)}</strong></article><article className="sigiu-module-kpi"><small>{termos.pagamento}</small><strong>{moeda(dados.resumo?.pago)}</strong></article></section>
    <nav className="sigiu-tabs"><button className={`sigiu-tab ${aba==="compromissos"?"is-active":""}`} onClick={()=>setAba("compromissos")}>Compromissos</button><button className={`sigiu-tab ${aba==="orcamento"?"is-active":""}`} onClick={()=>setAba("orcamento")}>Planejamento orçamentário</button><button className={`sigiu-tab ${aba==="fluxo"?"is-active":""}`} onClick={()=>setAba("fluxo")}>Fluxo e deduções</button><button className={`sigiu-tab ${aba==="cadastros"?"is-active":""}`} onClick={()=>setAba("cadastros")}>Centros e fontes</button></nav>
    <div className="sigiu-planning-toolbar"><input aria-label="Pesquisar financeiro" placeholder="Pesquisar código, descrição ou beneficiário" value={filtro} onChange={e=>setFiltro(e.target.value)}/><select aria-label="Ano financeiro" value={ano} onChange={e=>setAno(Number(e.target.value))}>{[ano-1,ano,ano+1].filter((x,i,a)=>a.indexOf(x)===i).sort().map(x=><option key={x}>{x}</option>)}</select></div>
    {carregando?<div className="sigiu-empty">Carregando execução financeira…</div>:<>
      {aba==="compromissos"&&<div className="sigiu-planning-table"><table><thead><tr><th>Compromisso</th><th>Origem</th><th>Vencimento</th><th>Valor</th><th>Liquidado</th><th>Pago</th><th>Status</th><th></th></tr></thead><tbody>{compromissos.map(item=><tr key={item.id} onClick={()=>abrir(item)}><td><b>{item.codigo}</b><span>{item.descricao}<br/><small>{item.beneficiario||"Sem beneficiário"}</small></span></td><td>{titulo(item.origemTipo)}</td><td>{item.dataVencimento||"—"}</td><td>{moeda(item.valorTotal)}</td><td>{moeda(item.resumo?.liquidadoBruto)}</td><td>{moeda(item.resumo?.pago)}</td><td><span className={`sigiu-status status-${item.status}`}>{STATUS[item.status]}</span></td><td><button className="sigiu-link">Abrir</button></td></tr>)}</tbody></table>{!compromissos.length&&<div className="sigiu-empty">Nenhum compromisso financeiro encontrado.</div>}</div>}
      {aba==="orcamento"&&<div className="sigiu-planning-cards"><div className="sigiu-section-title"><div><h2>{termos.orçamento} anual</h2><p>Distribuição por centro de custo, fonte e natureza CAPEX/OPEX.</p></div><button onClick={()=>setModal("orcamento")}>+ Nova previsão</button></div>{dados.orcamentos.map(item=><article key={item.id}><span>{item.classificacao.toUpperCase()} · {item.codigo}</span><h3>{item.descricao}</h3><p>{dados.centros.find(x=>x.id===item.costCenterId)?.nome||"Centro de custo"} · {dados.fontes.find(x=>x.id===item.fundingSourceId)?.nome||"Fonte"}</p><div className="sigiu-progress"><i style={{width:`${Math.min(100,item.valorAtual?item.consumido/item.valorAtual*100:0)}%`}}/></div><footer><small>Consumido {moeda(item.consumido)}</small><strong>{moeda(item.disponivel)}</strong></footer></article>)}{!dados.orcamentos.length&&<div className="sigiu-empty">Cadastre centro, fonte e orçamento para iniciar.</div>}</div>}
      {aba==="fluxo"&&<><section className="sigiu-contract-summary"><article><span>Disponível</span><strong>{moeda(dados.resumo?.disponivel)}</strong></article><article><span>Retenções</span><strong>{moeda(dados.resumo?.retencoes)}</strong></article><article><span>Glosas</span><strong>{moeda(dados.resumo?.glosas)}</strong></article><article><span>CAPEX / OPEX</span><strong>{moeda(dados.resumo?.capex)} / {moeda(dados.resumo?.opex)}</strong></article></section><div className="sigiu-planning-table"><table><thead><tr><th>Previsão de caixa</th><th>Competência</th><th>Vencimento</th><th>Saldo a liquidar</th><th>Saldo a pagar</th><th>Status</th></tr></thead><tbody>{compromissos.filter(x=>!["pago","cancelado"].includes(x.status)).sort((a,b)=>(a.dataVencimento||"9999").localeCompare(b.dataVencimento||"9999")).map(item=><tr key={item.id} onClick={()=>abrir(item)}><td><b>{item.codigo}</b><span>{item.descricao}</span></td><td>{item.competencia}</td><td>{item.dataVencimento||"—"}</td><td>{moeda(item.resumo.saldoCompromisso)}</td><td>{moeda(item.resumo.saldoAPagar)}</td><td>{STATUS[item.status]}</td></tr>)}</tbody></table></div></>}
      {aba==="cadastros"&&<section className="sigiu-contract-detail-grid"><div><div className="sigiu-section-title"><h2>Centros de custo</h2><button onClick={()=>setModal("centro")}>+ Adicionar</button></div>{dados.centros.map(item=><article key={item.id}><b>{item.codigo} · {item.nome}</b><span>{item.responsavel||"Sem responsável"} · {item.status}</span></article>)}{!dados.centros.length&&<p>Nenhum centro de custo cadastrado.</p>}</div><div><div className="sigiu-section-title"><h2>Fontes de recursos</h2><button onClick={()=>setModal("fonte")}>+ Adicionar</button></div>{dados.fontes.map(item=><article key={item.id}><b>{item.codigo} · {item.nome}</b><span>{titulo(item.tipo)} · {item.status}</span></article>)}{!dados.fontes.length&&<p>Nenhuma fonte cadastrada.</p>}</div></section>}
    </>}
    {selecionado&&<div className="sigiu-drawer-backdrop" onClick={()=>setSelecionado(null)}><aside className="sigiu-planning-drawer sigiu-contract-drawer" onClick={e=>e.stopPropagation()}><header><div><span className="sigiu-page-eyebrow">{selecionado.codigo} · {STATUS[selecionado.status]}</span><h2>{selecionado.descricao}</h2><p>{selecionado.beneficiario||"Sem beneficiário informado"}</p></div><button aria-label="Fechar" onClick={()=>setSelecionado(null)}>×</button></header><section className="sigiu-contract-summary"><article><span>Valor total</span><strong>{moeda(selecionado.valorTotal)}</strong></article><article><span>Liquidado líquido</span><strong>{moeda(selecionado.resumo.liquidadoLiquido)}</strong></article><article><span>Pago</span><strong>{moeda(selecionado.resumo.pago)}</strong></article><article><span>Saldo a pagar</span><strong>{moeda(selecionado.resumo.saldoAPagar)}</strong></article></section><div className="sigiu-detail-actions">{acoes.map(([id,label])=><button key={id} className={id==="cancelamento"?"danger":""} onClick={()=>abrirOperacao(id)}>{label}</button>)}</div><section className="sigiu-timeline"><h3>Movimentos financeiros</h3>{selecionado.movimentos.map(item=><article key={item.id}><i/><div><b>{titulo(item.tipo)} · {moeda(item.valor)}</b><span>{item.dataMovimento} · líquido {moeda(item.valorLiquido)}</span><p>{item.documento||item.justificativa||"Movimento registrado"}{item.retencoes>0&&` · retenções ${moeda(item.retencoes)}`}{item.glosas>0&&` · glosas ${moeda(item.glosas)}`}</p>{item.tipo==="pagamento"&&<button className="sigiu-link" onClick={()=>{setMovimentoSelecionado(item);setModal("conciliacao");}}>Conciliar</button>}{item.conciliacoes?.map(c=><small key={c.id}>{c.status} · {c.referenciaExterna} · diferença {moeda(c.diferenca)}</small>)}</div></article>)}{!selecionado.movimentos.length&&<p>Nenhum movimento registrado.</p>}</section></aside></div>}
    {modal&&<div className="sigiu-modal-backdrop"><form className="sigiu-modal sigiu-planning-small" onSubmit={salvar}><header><div><span className="sigiu-page-eyebrow">Financeiro-orçamentário</span><h2>{{centro:"Novo centro de custo",fonte:"Nova fonte de recursos",orcamento:`Nova ${termos.orçamento.toLocaleLowerCase("pt-BR")}`,compromisso:"Novo compromisso",movimento:titulo(operacao),conciliacao:"Conciliar pagamento"}[modal]}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></header><div className="sigiu-form-grid">
      {modal==="centro"&&<><label>Código<input name="codigo" required defaultValue={proximo("CC",dados.centros)}/></label><label className="span-2">Nome<input name="nome" required/></label><label className="span-2">Responsável<input name="responsavel"/></label><label>Status<select name="status"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></label></>}
      {modal==="fonte"&&<><label>Código<input name="codigo" required defaultValue={proximo("FR",dados.fontes)}/></label><label className="span-2">Nome<input name="nome" required/></label><label>Tipo<select name="tipo"><option value="tesouro">Tesouro</option><option value="transferencia">Transferência</option><option value="convenio">Convênio</option><option value="propria">Recursos próprios</option><option value="financiamento">Financiamento</option><option value="outra">Outra</option></select></label></>}
      {modal==="orcamento"&&<><label>Centro de custo<select name="costCenterId" required><option value="">Selecione</option>{dados.centros.filter(x=>x.status==="ativo").map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></label><label>Fonte<select name="fundingSourceId" required><option value="">Selecione</option>{dados.fontes.filter(x=>x.status==="ativa").map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></label><label>Código<input name="codigo" required defaultValue={proximo("ORC",dados.orcamentos)}/></label><label>Ano<input name="ano" type="number" required defaultValue={ano}/></label><label>Natureza<select name="classificacao"><option value="capex">CAPEX</option><option value="opex">OPEX</option></select></label><label>Valor inicial<input name="valorInicial" type="number" min="0" step="0.01" required/></label><label>Ajustes<input name="ajustes" type="number" step="0.01" defaultValue="0"/></label><label className="span-2">Descrição<input name="descricao" required/></label></>}
      {modal==="compromisso"&&<><label>{termos.orçamento}<select name="budgetId" required><option value="">Selecione</option>{dados.orcamentos.filter(x=>x.status==="ativo"&&x.disponivel>0).map(x=><option key={x.id} value={x.id}>{x.codigo} · disponível {moeda(x.disponivel)}</option>)}</select></label><label>Código<input name="codigo" required defaultValue={proximo("CF",dados.compromissos)}/></label><label>Competência<input name="competencia" type="date" required defaultValue={hoje()}/></label><label>Origem<select name="origemId"><option value="">Registro manual</option>{origens.map(x=><option key={`${x.tipo}-${x.id}`} value={x.id}>{x.label}</option>)}</select></label><label>Beneficiário<input name="beneficiario"/></label><label>Vencimento<input name="dataVencimento" type="date"/></label><label>Valor<input name="valorTotal" type="number" min="0.01" step="0.01" required/></label><label className="span-2">Descrição<textarea name="descricao" required/></label><input type="hidden" name="origemTipo" value="manual"/></>}
      {modal==="movimento"&&<><label>Data<input name="dataMovimento" type="date" defaultValue={hoje()}/></label>{operacao!=="cancelamento"&&<label>Valor<input name="valor" type="number" min="0.01" max={operacao==="liquidacao"?selecionado.resumo.saldoCompromisso:operacao==="pagamento"?selecionado.resumo.saldoAPagar:selecionado.valorTotal} step="0.01" required defaultValue={["reserva","compromisso"].includes(operacao)?selecionado.valorTotal:""}/></label>}{operacao==="liquidacao"&&<><label>Retenções<input name="retencoes" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Glosas<input name="glosas" type="number" min="0" step="0.01" defaultValue="0"/></label></>}<label>Documento<input name="documento"/></label><label>Referência externa<input name="referenciaExterna"/></label><label className="span-2">Justificativa<textarea name="justificativa" required={operacao==="cancelamento"}/></label></>}
      {modal==="conciliacao"&&<><label>Referência externa<input name="referenciaExterna" required defaultValue={movimentoSelecionado?.referenciaExterna}/></label><label>Data<input name="dataConciliacao" type="date" defaultValue={hoje()}/></label><label>Status<select name="status"><option value="conciliado">Conciliado</option><option value="divergente">Divergente</option><option value="pendente">Pendente</option></select></label><label>Diferença<input name="diferenca" type="number" step="0.01" defaultValue="0"/></label><label className="span-2">Observação<textarea name="observacao"/></label></>}
    </div><footer><button type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando?"Salvando…":"Confirmar"}</button></footer></form></div>}
  </div>;
}
