import { useEffect,useMemo,useState } from "react";
import { criarClientePrumo,obterConfiguracaoInfraestrutura,obterContextoDesenvolvimento } from "../services/infraestruturaCorporativa";
import { useContextoPatrimonial } from "../contexts/ContextoPatrimonialContext";
const chave=()=>crypto.randomUUID();const hoje=()=>new Date().toISOString().slice(0,10);const titulo=v=>String(v||"").replaceAll("_"," ").replace(/^./,x=>x.toUpperCase());
const proximo=(p,itens)=>`${p}-${String(itens.reduce((m,x)=>Math.max(m,Number(String(x.codigo||"").match(/(\d+)$/)?.[1])||0),0)+1).padStart(3,"0")}`;

export default function Regularidade(){
 const contextoPatrimonial=useContextoPatrimonial();
 const cliente=useMemo(()=>{const c=obterConfiguracaoInfraestrutura();return c.apiConfigurada?criarClientePrumo({baseUrl:c.apiUrl,obterContexto:()=>obterContextoDesenvolvimento()}):null;},[]);
 const [dados,setDados]=useState({requisitos:[],riscos:[],publicacoes:[],unidades:[],resumo:{}}),[aba,setAba]=useState("requisitos"),[modal,setModal]=useState(""),[risco,setRisco]=useState(null),[mensagem,setMensagem]=useState(""),[salvando,setSalvando]=useState(false);
 async function carregar(){if(!cliente)return;try{const [requisitos,riscos,publicacoes,unidades,resumo]=await Promise.all([cliente.listarRequisitosCompliance(),cliente.listarRiscosCompliance(),cliente.listarPublicacoesTransparencia(),cliente.listarUnidadesPatrimoniais({tipo:"sala"}),cliente.obterResumoCompliance()]);setDados({requisitos,riscos,publicacoes,unidades,resumo});setMensagem("");}catch(e){setMensagem(e.message);}}
 useEffect(()=>{carregar();},[]);
 const requisitosEscopo=useMemo(()=>dados.requisitos.filter(x=>contextoPatrimonial.estaNoEscopo(x.patrimonioUnidadeId)),[dados.requisitos,contextoPatrimonial.idsEscopo]);
 async function salvar(e){e.preventDefault();setSalvando(true);const f=Object.fromEntries(new FormData(e.currentTarget));try{
  if(modal==="requisito")await cliente.criarRequisitoCompliance({...f,dados:{}},chave());
  if(modal==="risco")await cliente.criarRiscoCompliance({...f,probabilidade:Number(f.probabilidade),impacto:Number(f.impacto),dados:{}},chave());
  if(modal==="acao")await cliente.criarAcaoCompliance(risco.id,{...f,percentual:Number(f.percentual||0),dados:{}},chave());
  if(modal==="auditoria")await cliente.registrarAuditoriaCompliance({...f,evidencias:[],dados:{}},chave());
  if(modal==="publicacao")await cliente.criarPublicacaoTransparencia({...f,conteudo:{resumo:f.descricaoPublica},dadosInternos:{}},chave());
  setModal("");setRisco(null);await carregar();
 }catch(err){setMensagem(err.message);}finally{setSalvando(false);}}
 async function publicar(x){try{await cliente.publicarTransparencia(x.id,x.versao);await carregar();}catch(e){setMensagem(e.message);}}
 const r=dados.resumo;
 return <div className="sigiu-page sigiu-regularidade"><header className="sigiu-page-heading sigiu-page-heading--modulo"><div><span className="sigiu-page-eyebrow">Governança e compliance</span><h1>Regularidade e compliance</h1><p>Licenças, PPCI, ART/RRT, riscos, controles, auditorias e transparência autorizada.</p></div><button className="sigiu-primary" onClick={()=>setModal("requisito")}>+ Novo requisito</button></header>{mensagem&&<div className="sigiu-feedback">{mensagem}</div>}{contextoPatrimonial.unidadeAtiva&&<div className="sigiu-context-scope-notice">Exibindo o contexto: <strong>{contextoPatrimonial.unidadeAtiva.nome}</strong></div>}
 <section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>Requisitos</small><strong>{r.requisitos||0}</strong><em>{r.regulares||0} regulares</em></article><article className="sigiu-module-kpi sigiu-module-kpi--warning"><small>A vencer</small><strong>{r.aVencer||0}</strong></article><article className="sigiu-module-kpi"><small>Vencidos</small><strong>{r.vencidos||0}</strong></article><article className="sigiu-module-kpi"><small>Riscos críticos</small><strong>{r.riscosCriticos||0}</strong></article></section>
 <nav className="sigiu-tabs"><button className={`sigiu-tab ${aba==="requisitos"?"is-active":""}`} onClick={()=>setAba("requisitos")}>Regularidade</button><button className={`sigiu-tab ${aba==="riscos"?"is-active":""}`} onClick={()=>setAba("riscos")}>Riscos e controles</button><button className={`sigiu-tab ${aba==="auditorias"?"is-active":""}`} onClick={()=>setAba("auditorias")}>Auditorias</button><button className={`sigiu-tab ${aba==="transparencia"?"is-active":""}`} onClick={()=>setAba("transparencia")}>Transparência</button></nav>
 {aba==="requisitos"&&<div className="sigiu-planning-table"><table><thead><tr><th>Requisito</th><th>Local</th><th>Documento / órgão</th><th>Validade</th><th>Criticidade</th><th>Status</th></tr></thead><tbody>{requisitosEscopo.map(x=><tr key={x.id}><td><b>{x.codigo}</b><span>{x.titulo}<br/><small>{titulo(x.tipo)}</small></span></td><td>{dados.unidades.find(u=>u.id===x.patrimonioUnidadeId)?.nome||"Local cadastrado"}</td><td>{x.numeroDocumento||"—"}<br/><small>{x.orgaoEmissor}</small></td><td>{x.dataValidade||"Sem validade"}</td><td>{titulo(x.criticidade)}</td><td><span className={`sigiu-status status-${x.status}`}>{titulo(x.status)}</span></td></tr>)}</tbody></table>{!requisitosEscopo.length&&<div className="sigiu-empty">Nenhum requisito neste contexto.</div>}</div>}
 {aba==="riscos"&&<div className="sigiu-planning-cards"><div className="sigiu-section-title"><div><h2>Matriz de riscos e controles</h2><p>Probabilidade × impacto, responsáveis e tratamento.</p></div><button onClick={()=>setModal("risco")}>+ Novo risco</button></div>{dados.riscos.map(x=><article key={x.id}><span>{x.codigo} · NÍVEL {x.nivel}</span><h3>{x.titulo}</h3><p>{x.descricao}</p><small>Controle: {x.controle||"não definido"}</small><footer><span>{titulo(x.status)}</span><button className="sigiu-link" onClick={()=>{setRisco(x);setModal("acao");}}>+ Plano de ação</button></footer></article>)}{!dados.riscos.length&&<div className="sigiu-empty">Nenhum risco cadastrado.</div>}</div>}
 {aba==="auditorias"&&<section className="sigiu-card"><div className="sigiu-section-title"><div><h2>Auditorias e evidências</h2><p>Registros imutáveis, escopo, conclusão e classificação.</p></div><button onClick={()=>setModal("auditoria")}>+ Registrar auditoria</button></div><div className="sigiu-empty">As auditorias registradas ficam preservadas no histórico e na trilha corporativa.</div></section>}
 {aba==="transparencia"&&<section><div className="sigiu-section-title"><div><h2>Publicações autorizadas</h2><p>Somente conteúdo sanitizado e aprovado é disponibilizado.</p></div><button onClick={()=>setModal("publicacao")}>+ Nova publicação</button></div><div className="sigiu-planning-table"><table><thead><tr><th>Publicação</th><th>Categoria</th><th>Período</th><th>Status</th><th>Ação</th></tr></thead><tbody>{dados.publicacoes.map(x=><tr key={x.id}><td><b>{x.codigo}</b><span>{x.titulo}<br/><small>{x.descricaoPublica}</small></span></td><td>{x.categoria}</td><td>{x.periodoReferencia||"—"}</td><td>{titulo(x.status)}</td><td>{x.status==="rascunho"&&<button className="sigiu-link" onClick={()=>publicar(x)}>Publicar</button>}</td></tr>)}</tbody></table></div></section>}
 {modal&&<div className="sigiu-modal-backdrop"><form className="sigiu-modal sigiu-planning-small" onSubmit={salvar}><header><div><span className="sigiu-page-eyebrow">Regularidade e compliance</span><h2>{{requisito:"Novo requisito",risco:"Novo risco",acao:"Plano de ação",auditoria:"Registrar auditoria",publicacao:"Nova publicação"}[modal]}</h2></div><button type="button" onClick={()=>setModal("")}>×</button></header><div className="sigiu-form-grid">
 {modal==="requisito"&&<><label>Local<select name="patrimonioUnidadeId" required><option value="">Selecione</option>{dados.unidades.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></label><label>Código<input name="codigo" required defaultValue={proximo("REG",dados.requisitos)}/></label><label>Tipo<select name="tipo"><option value="ppci">PPCI</option><option value="licenca_operacao">Licença de operação</option><option value="art_rrt">ART/RRT</option><option value="alvara">Alvará</option><option value="acessibilidade">Acessibilidade</option><option value="outro">Outro</option></select></label><label className="span-2">Título<input name="titulo" required/></label><label>Órgão emissor<input name="orgaoEmissor"/></label><label>Nº documento<input name="numeroDocumento"/></label><label>Emissão<input name="dataEmissao" type="date"/></label><label>Validade<input name="dataValidade" type="date"/></label><label>Responsável<input name="responsavel"/></label><label>Criticidade<select name="criticidade"><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option><option value="baixa">Baixa</option></select></label></>}
 {modal==="risco"&&<><label>Código<input name="codigo" required defaultValue={proximo("RSC",dados.riscos)}/></label><label className="span-2">Título<input name="titulo" required/></label><label>Probabilidade<select name="probabilidade">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Impacto<select name="impacto">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Responsável<input name="responsavel"/></label><label className="span-2">Descrição<textarea name="descricao" required/></label><label className="span-2">Controle existente<textarea name="controle"/></label></>}
 {modal==="acao"&&<><label className="span-2">Risco<input readOnly value={risco?.titulo||""}/></label><label className="span-2">Título<input name="titulo" required/></label><label>Responsável<input name="responsavel" required/></label><label>Prazo<input name="prazo" type="date" required/></label><label>Progresso %<input name="percentual" type="number" min="0" max="100" defaultValue="0"/></label><label className="span-2">Descrição<textarea name="descricao" required/></label></>}
 {modal==="auditoria"&&<><label>Código<input name="codigo" required defaultValue={`AUD-${Date.now().toString().slice(-5)}`}/></label><label className="span-2">Título<input name="titulo" required/></label><label>Data<input name="dataAuditoria" type="date" required defaultValue={hoje()}/></label><label>Auditor<input name="auditor" required/></label><label>Classificação<select name="classificacao"><option value="conforme">Conforme</option><option value="ressalva">Com ressalva</option><option value="nao_conforme">Não conforme</option></select></label><label className="span-2">Escopo<textarea name="escopo" required/></label><label className="span-2">Conclusão<textarea name="conclusao" required/></label></>}
 {modal==="publicacao"&&<><label>Código<input name="codigo" required defaultValue={proximo("PUB",dados.publicacoes)}/></label><label>Categoria<input name="categoria" required/></label><label>Período<input name="periodoReferencia"/></label><label className="span-2">Título<input name="titulo" required/></label><label className="span-2">Descrição pública<textarea name="descricaoPublica" required/></label></>}
 </div><footer><button type="button" onClick={()=>setModal("")}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando?"Salvando…":"Confirmar"}</button></footer></form></div>}</div>;
}
