import { useEffect, useMemo, useState } from "react";
import { criarClientePrumo, obterConfiguracaoInfraestrutura, obterContextoDesenvolvimento } from "../services/infraestruturaCorporativa";
import { useContextoPatrimonial } from "../contexts/ContextoPatrimonialContext";
import ResponsavelSelect from "../components/Forms/ResponsavelSelect";

const chave = () => crypto.randomUUID();
const hoje = () => new Date().toISOString().slice(0, 10);
const titulo = (v) => String(v || "").replaceAll("_", " ").replace(/^./, (x) => x.toUpperCase());
const data = (valor) => valor ? String(valor).slice(0, 10) : "";
const limpar = (form) => Object.fromEntries([...new FormData(form)].filter(([, valor]) => valor !== ""));
const proximo = (prefixo, itens) => `${prefixo}-${String(itens.reduce((m, x) => Math.max(m, Number(String(x.codigo || "").match(/(\d+)$/)?.[1]) || 0), 0) + 1).padStart(3, "0")}`;

export default function Regularidade({ onAbrirGed }) {
  const patrimonio = useContextoPatrimonial();
  const cliente = useMemo(() => {
    const cfg = obterConfiguracaoInfraestrutura();
    return cfg.apiConfigurada ? criarClientePrumo({ baseUrl: cfg.apiUrl, obterContexto: () => obterContextoDesenvolvimento() }) : null;
  }, []);
  const [dados, setDados] = useState({ requisitos: [], ppcis: [], riscos: [], publicacoes: [], unidades: [], ativos: [], resumo: {}, resumoPpci: {} });
  const [aba, setAba] = useState("regularidade");
  const [modal, setModal] = useState("");
  const [selecionado, setSelecionado] = useState(null);
  const [risco, setRisco] = useState(null);
  const [mensagem, setMensagem] = useState("");
  const [salvando, setSalvando] = useState(false);
  const [responsaveis, setResponsaveis] = useState({ usuarios: [], equipes: [] });
  const [sistemaEdicao, setSistemaEdicao] = useState(null);

  async function carregar() {
    if (!cliente) return;
    try {
      const [requisitos, ppcis, riscos, publicacoes, unidades, ativos, resumo, resumoPpci, listaResponsaveis] = await Promise.all([
        cliente.listarRequisitosCompliance(), cliente.listarPpcis(), cliente.listarRiscosCompliance(),
        cliente.listarPublicacoesTransparencia(), cliente.listarUnidadesPatrimoniais(), cliente.listarAtivosPatrimoniais(), cliente.obterResumoCompliance(), cliente.obterResumoPpci(), cliente.listarResponsaveisCorporativos(),
      ]);
      setDados({ requisitos, ppcis, riscos, publicacoes, unidades, ativos, resumo, resumoPpci });
      setResponsaveis(listaResponsaveis);
      if (selecionado) setSelecionado(await cliente.obterPpci(selecionado.id));
      setMensagem("");
    } catch (erro) { setMensagem(erro.message); }
  }
  useEffect(() => { carregar(); }, []);

  const requisitos = useMemo(() => dados.requisitos.filter((x) => patrimonio.estaNoEscopo(x.patrimonioUnidadeId)), [dados.requisitos, patrimonio.idsEscopo]);
  const ppcis = useMemo(() => dados.ppcis.filter((x) => patrimonio.estaNoEscopo(x.patrimonioUnidadeId)), [dados.ppcis, patrimonio.idsEscopo]);
  const unidadesPpci = dados.unidades.filter((x) => ["site", "predio", "sala"].includes(x.nivel) && x.status === "ativo" && patrimonio.estaNoEscopo(x.id));
  const ativosPpci = dados.ativos.filter((x) => x.status !== "baixado" && patrimonio.estaNoEscopo(x.salaId));
  const nomeLocal = (id) => dados.unidades.find((x) => x.id === id)?.nome || "Local cadastrado";

  async function salvar(evento) {
    evento.preventDefault(); setSalvando(true); const f = limpar(evento.currentTarget);
    try {
      if (modal === "requisito") await cliente.criarRequisitoCompliance({ ...f, dados: {} }, chave());
      if (modal === "ppci") {
        const payload = { ...f, areaProtegidaM2: f.areaProtegidaM2 ? Number(f.areaProtegidaM2) : undefined, dados: {} };
        if (selecionado) await cliente.atualizarPpci(selecionado.id, payload, selecionado.versao);
        else await cliente.criarPpci(payload, chave());
      }
      if (modal === "sistema") {
        const payload = { ...f, quantidade: Number(f.quantidade || 0), dados: {} };
        if (sistemaEdicao) await cliente.atualizarSistemaPpci(selecionado.id, sistemaEdicao.id, payload, sistemaEdicao.versao);
        else await cliente.criarSistemaPpci(selecionado.id, payload, chave());
      }
      if (modal === "inspecao") await cliente.registrarInspecaoPpci(selecionado.id, { ...f, evidencias: [] }, chave());
      if (modal === "risco") await cliente.criarRiscoCompliance({ ...f, probabilidade: Number(f.probabilidade), impacto: Number(f.impacto), dados: {} }, chave());
      if (modal === "acao") await cliente.criarAcaoCompliance(risco.id, { ...f, percentual: Number(f.percentual || 0), dados: {} }, chave());
      if (modal === "auditoria") await cliente.registrarAuditoriaCompliance({ ...f, evidencias: [], dados: {} }, chave());
      if (modal === "publicacao") await cliente.criarPublicacaoTransparencia({ ...f, conteudo: { resumo: f.descricaoPublica }, dadosInternos: {} }, chave());
      setModal(""); setRisco(null); setSistemaEdicao(null); await carregar();
    } catch (erro) { setMensagem(erro.message); } finally { setSalvando(false); }
  }
  async function abrirPpci(item) { try { setSelecionado(await cliente.obterPpci(item.id)); } catch (erro) { setMensagem(erro.message); } }
  async function publicar(item) { try { await cliente.publicarTransparencia(item.id, item.versao); await carregar(); } catch (erro) { setMensagem(erro.message); } }
  async function removerSistema(item) { const motivo=globalThis.prompt("Informe o motivo da remoção do sistema preventivo:");if(!motivo?.trim())return;try{const resultado=await cliente.removerSistemaPpci(selecionado.id,item.id,motivo.trim(),item.versao);setMensagem(resultado.modo==="inativado"?"Sistema inativado; inspeções e histórico foram preservados.":"Sistema removido com sucesso.");await carregar();}catch(erro){setMensagem(erro.message);} }
  const r = dados.resumo, rp = dados.resumoPpci;

  return <div className="sigiu-page sigiu-regularidade">
    <header className="sigiu-page-heading sigiu-page-heading--modulo"><div><span className="sigiu-page-eyebrow">Governança técnica e segurança predial</span><h1>Regularidade</h1><p>Licenças, PPCI, sistemas preventivos, riscos, auditorias e transparência em uma base corporativa única.</p></div><button className="sigiu-primary" onClick={() => { setSelecionado(null); setModal(aba === "ppci" ? "ppci" : "requisito"); }}>+ {aba === "ppci" ? "Novo PPCI" : "Novo requisito"}</button></header>
    {mensagem && <div className="sigiu-feedback">{mensagem}</div>}
    {patrimonio.unidadeAtiva && <div className="sigiu-context-scope-notice">Exibindo o contexto: <strong>{patrimonio.unidadeAtiva.nome}</strong></div>}
    <section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>Requisitos</small><strong>{r.requisitos || 0}</strong><em>{r.regulares || 0} regulares</em></article><article className="sigiu-module-kpi"><small>PPCIs locais</small><strong>{rp.total || 0}</strong><em>{rp.regulares || 0} regulares</em></article><article className="sigiu-module-kpi sigiu-module-kpi--warning"><small>A vencer</small><strong>{(r.aVencer || 0) + (rp.aVencer || 0)}</strong></article><article className="sigiu-module-kpi"><small>Vencidos</small><strong>{(r.vencidos || 0) + (rp.vencidos || 0)}</strong></article><article className="sigiu-module-kpi"><small>Riscos críticos</small><strong>{r.riscosCriticos || 0}</strong></article></section>
    <nav className="sigiu-tabs sigiu-domain-tabs">{[["regularidade","Licenças e requisitos"],["ppci","PPCI e segurança"],["riscos","Riscos e controles"],["auditorias","Auditorias"],["transparencia","Transparência"]].map(([id, rotulo]) => <button key={id} className={`sigiu-tab ${aba === id ? "is-active" : ""}`} onClick={() => { setAba(id); setSelecionado(null); }}>{rotulo}</button>)}</nav>

    {aba === "regularidade" && <div className="sigiu-planning-table"><table><thead><tr><th>Requisito</th><th>Local patrimonial</th><th>Documento / órgão</th><th>Validade</th><th>Criticidade</th><th>Status</th></tr></thead><tbody>{requisitos.map((x) => <tr key={x.id}><td><b>{x.codigo}</b><span>{x.titulo}<br/><small>{titulo(x.tipo)}</small></span></td><td>{nomeLocal(x.patrimonioUnidadeId)}</td><td>{x.numeroDocumento || "—"}<br/><small>{x.orgaoEmissor}</small></td><td>{data(x.dataValidade) || "Sem validade"}</td><td>{titulo(x.criticidade)}</td><td><span className={`sigiu-status status-${x.status}`}>{titulo(x.status)}</span></td></tr>)}</tbody></table>{!requisitos.length && <div className="sigiu-empty">Nenhum requisito neste contexto.</div>}</div>}

    {aba === "ppci" && !selecionado && <><div className="sigiu-section-title"><div><h2>Processos PPCI</h2><p>Fonte local PostgreSQL vinculada a Site, Prédio, Sala e ativos.</p></div><button onClick={() => setModal("ppci")}>+ Novo PPCI</button></div><div className="sigiu-planning-table"><table><thead><tr><th>PPCI / processo</th><th>Local</th><th>Fase</th><th>Validade</th><th>Responsável</th><th>Status</th></tr></thead><tbody>{ppcis.map((x) => <tr key={x.id} onClick={() => abrirPpci(x)} className="sigiu-clickable-row"><td><b>{x.codigo}</b><span>{x.titulo}<br/><small>{x.numeroProcesso || "Sem protocolo"}</small></span></td><td>{x.local || nomeLocal(x.patrimonioUnidadeId)}<br/><small>{titulo(x.localNivel)}</small></td><td>{titulo(x.fase)}</td><td>{data(x.dataValidade) || "Sem validade"}</td><td>{x.responsavel || "—"}</td><td><span className={`sigiu-status status-${x.statusCalculado}`}>{titulo(x.statusCalculado)}</span></td></tr>)}</tbody></table>{!ppcis.length && <div className="sigiu-empty">Nenhum PPCI cadastrado neste contexto.</div>}</div></>}

    {aba === "ppci" && selecionado && <section><div className="sigiu-section-title"><div><button className="sigiu-link" onClick={() => setSelecionado(null)}>← Todos os PPCIs</button><h2>{selecionado.codigo} · {selecionado.titulo}</h2><p>{selecionado.local} · {selecionado.numeroProcesso || "Processo ainda não protocolado"}</p></div><div className="sigiu-inline-actions"><button onClick={() => onAbrirGed?.({moduleId:"regularidade",entidadeTipo:"ppci",entidadeId:selecionado.id})}>Documentos no GED</button><button onClick={() => setModal("ppci")}>Editar PPCI</button></div></div><section className="sigiu-module-kpis"><article className="sigiu-module-kpi"><small>Fase</small><strong>{titulo(selecionado.fase)}</strong></article><article className="sigiu-module-kpi"><small>Status</small><strong>{titulo(selecionado.statusCalculado)}</strong></article><article className="sigiu-module-kpi"><small>Validade</small><strong>{data(selecionado.dataValidade) || "—"}</strong></article><article className="sigiu-module-kpi"><small>Área protegida</small><strong>{selecionado.areaProtegidaM2 || 0} m²</strong></article></section><div className="sigiu-planning-cards"><div className="sigiu-section-title"><div><h2>Sistemas preventivos</h2><p>Equipamentos e subsistemas vinculados ao local ou ativo.</p></div><button onClick={() => { setSistemaEdicao(null); setModal("sistema"); }}>+ Sistema</button></div>{(selecionado.sistemas || []).map((x) => <article key={x.id}><span>{titulo(x.tipo)}</span><h3>{x.descricao}</h3><p>{x.quantidade} {x.unidade} · {nomeLocal(x.patrimonioUnidadeId)}</p><footer><span>{titulo(x.conformidade)}</span><small>Próxima inspeção: {data(x.proximaInspecao) || "não programada"}</small></footer><div className="sigiu-inline-actions"><button type="button" className="sigiu-link" onClick={()=>{setSistemaEdicao(x);setModal("sistema");}}>Editar</button><button type="button" className="sigiu-link danger" onClick={()=>removerSistema(x)}>Remover</button><button type="button" className="sigiu-link" onClick={()=>onAbrirGed?.({moduleId:"regularidade",entidadeTipo:"sistema_ppci",entidadeId:x.id})}>GED</button></div></article>)}{!selecionado.sistemas?.length && <div className="sigiu-empty">Nenhum sistema preventivo cadastrado.</div>}</div><section className="sigiu-card"><div className="sigiu-section-title"><div><h2>Inspeções</h2><p>Histórico imutável de verificações, testes e vistorias.</p></div><button onClick={() => setModal("inspecao")}>+ Inspeção</button></div><div className="sigiu-planning-table"><table><thead><tr><th>Data</th><th>Tipo</th><th>Resultado</th><th>Inspetor</th><th>Observações</th></tr></thead><tbody>{(selecionado.inspecoes || []).map((x) => <tr key={x.id}><td>{data(x.dataInspecao)}</td><td>{titulo(x.tipo)}</td><td>{titulo(x.resultado)}</td><td>{x.inspetor}</td><td>{x.observacoes || "—"}</td></tr>)}</tbody></table></div></section></section>}

    {aba === "riscos" && <div className="sigiu-planning-cards"><div className="sigiu-section-title"><div><h2>Matriz de riscos e controles</h2><p>Riscos de todas as obrigações, inclusive PPCI.</p></div><button onClick={() => setModal("risco")}>+ Novo risco</button></div>{dados.riscos.map((x) => <article key={x.id}><span>{x.codigo} · NÍVEL {x.nivel}</span><h3>{x.titulo}</h3><p>{x.descricao}</p><small>Controle: {x.controle || "não definido"}</small><footer><span>{titulo(x.status)}</span><button className="sigiu-link" onClick={() => { setRisco(x); setModal("acao"); }}>+ Plano de ação</button></footer></article>)}</div>}
    {aba === "auditorias" && <section className="sigiu-card"><div className="sigiu-section-title"><div><h2>Auditorias e evidências</h2><p>Escopo, conclusão e classificação preservados na trilha corporativa.</p></div><button onClick={() => setModal("auditoria")}>+ Registrar auditoria</button></div></section>}
    {aba === "transparencia" && <section><div className="sigiu-section-title"><div><h2>Publicações autorizadas</h2><p>Somente conteúdo sanitizado e aprovado é disponibilizado.</p></div><button onClick={() => setModal("publicacao")}>+ Nova publicação</button></div><div className="sigiu-planning-table"><table><thead><tr><th>Publicação</th><th>Categoria</th><th>Período</th><th>Status</th><th>Ação</th></tr></thead><tbody>{dados.publicacoes.map((x) => <tr key={x.id}><td><b>{x.codigo}</b><span>{x.titulo}<br/><small>{x.descricaoPublica}</small></span></td><td>{x.categoria}</td><td>{x.periodoReferencia || "—"}</td><td>{titulo(x.status)}</td><td>{x.status === "rascunho" && <button className="sigiu-link" onClick={() => publicar(x)}>Publicar</button>}</td></tr>)}</tbody></table></div></section>}

    {modal && <div className="sigiu-modal-backdrop"><form className="sigiu-modal sigiu-planning-small" onSubmit={salvar}><header><div><span className="sigiu-page-eyebrow">Regularidade</span><h2>{{ requisito:"Novo requisito",ppci:selecionado?"Editar PPCI":"Novo PPCI",sistema:sistemaEdicao?"Editar sistema preventivo":"Novo sistema preventivo",inspecao:"Registrar inspeção",risco:"Novo risco",acao:"Plano de ação",auditoria:"Registrar auditoria",publicacao:"Nova publicação" }[modal]}</h2></div><button type="button" onClick={() => {setModal("");setSistemaEdicao(null);}}>×</button></header><div className="sigiu-form-grid">
      {modal === "requisito" && <><LocalSelect name="patrimonioUnidadeId" unidades={dados.unidades.filter((x) => x.status === "ativo")}/><label>Código<input name="codigo" required defaultValue={proximo("REG", dados.requisitos)}/></label><label>Tipo<select name="tipo"><option value="licenca_operacao">Licença de operação</option><option value="art_rrt">ART/RRT</option><option value="alvara">Alvará</option><option value="acessibilidade">Acessibilidade</option><option value="outro">Outro</option></select></label><label className="span-2">Título<input name="titulo" required/></label><label>Órgão emissor<input name="orgaoEmissor"/></label><label>Nº documento<input name="numeroDocumento"/></label><label>Emissão<input name="dataEmissao" type="date"/></label><label>Validade<input name="dataValidade" type="date"/></label><ResponsavelSelect responsaveis={responsaveis}/><label>Criticidade<select name="criticidade"><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option><option value="baixa">Baixa</option></select></label></>}
      {modal === "ppci" && <PpciForm item={selecionado} unidades={unidadesPpci} codigo={proximo("PPCI", dados.ppcis)} responsaveis={responsaveis}/>}
      {modal === "sistema" && <><LocalSelect name="patrimonioUnidadeId" unidades={unidadesPpci} padrao={sistemaEdicao?.patrimonioUnidadeId || selecionado?.patrimonioUnidadeId}/><label>Ativo vinculado (opcional)<select name="ativoId" defaultValue={sistemaEdicao?.ativoId || ""}><option value="">Sem ativo específico</option>{ativosPpci.map((x) => <option key={x.id} value={x.id}>{x.codigo} · {x.nome} · {nomeLocal(x.salaId)}</option>)}</select></label><label>Tipo<select name="tipo" defaultValue={sistemaEdicao?.tipo || "extintores"}><option value="extintores">Extintores</option><option value="hidrantes">Hidrantes</option><option value="alarme">Alarme</option><option value="deteccao">Detecção</option><option value="iluminacao">Iluminação</option><option value="sinalizacao">Sinalização</option><option value="saidas">Saídas</option><option value="sprinklers">Sprinklers</option><option value="spda">SPDA</option><option value="gas">Gás</option><option value="outro">Outro</option></select></label><label className="span-2">Descrição<input name="descricao" required defaultValue={sistemaEdicao?.descricao || ""}/></label><label>Quantidade<input name="quantidade" type="number" min="0" step="0.001" defaultValue={sistemaEdicao?.quantidade ?? 1}/></label><label>Unidade<input name="unidade" defaultValue={sistemaEdicao?.unidade || "un"}/></label><label>Conformidade<select name="conformidade" defaultValue={sistemaEdicao?.conformidade || "nao_avaliado"}><option value="nao_avaliado">Não avaliado</option><option value="conforme">Conforme</option><option value="nao_conforme">Não conforme</option><option value="nao_aplicavel">Não aplicável</option></select></label><label>Última inspeção<input name="ultimaInspecao" type="date" defaultValue={data(sistemaEdicao?.ultimaInspecao)}/></label><label>Próxima inspeção<input name="proximaInspecao" type="date" defaultValue={data(sistemaEdicao?.proximaInspecao)}/></label><ResponsavelSelect responsaveis={responsaveis} defaultValue={sistemaEdicao?.responsavel || ""}/></>}
      {modal === "inspecao" && <><label>Data<input name="dataInspecao" type="date" required defaultValue={hoje()}/></label><label>Tipo<select name="tipo"><option value="interna">Interna</option><option value="preventiva">Preventiva</option><option value="bombeiros">Bombeiros</option><option value="certificacao">Certificação</option><option value="teste">Teste</option></select></label><label>Resultado<select name="resultado"><option value="conforme">Conforme</option><option value="ressalva">Com ressalva</option><option value="nao_conforme">Não conforme</option></select></label><label>Inspetor<input name="inspetor" required/></label><label className="span-2">Observações<textarea name="observacoes"/></label></>}
      {modal === "risco" && <><label>Código<input name="codigo" required defaultValue={proximo("RSC", dados.riscos)}/></label><label className="span-2">Título<input name="titulo" required/></label><label>Probabilidade<select name="probabilidade">{[1,2,3,4,5].map((x) => <option key={x}>{x}</option>)}</select></label><label>Impacto<select name="impacto">{[1,2,3,4,5].map((x) => <option key={x}>{x}</option>)}</select></label><ResponsavelSelect responsaveis={responsaveis}/><label className="span-2">Descrição<textarea name="descricao" required/></label><label className="span-2">Controle existente<textarea name="controle"/></label></>}
      {modal === "acao" && <><label className="span-2">Risco<input readOnly value={risco?.titulo || ""}/></label><label className="span-2">Título<input name="titulo" required/></label><ResponsavelSelect responsaveis={responsaveis} required/><label>Prazo<input name="prazo" type="date" required/></label><label>Progresso %<input name="percentual" type="number" min="0" max="100" defaultValue="0"/></label><label className="span-2">Descrição<textarea name="descricao" required/></label></>}
      {modal === "auditoria" && <><label>Código<input name="codigo" required defaultValue={`AUD-${Date.now().toString().slice(-5)}`}/></label><label className="span-2">Título<input name="titulo" required/></label><label>Data<input name="dataAuditoria" type="date" required defaultValue={hoje()}/></label><label>Auditor<input name="auditor" required/></label><label>Classificação<select name="classificacao"><option value="conforme">Conforme</option><option value="ressalva">Com ressalva</option><option value="nao_conforme">Não conforme</option></select></label><label className="span-2">Escopo<textarea name="escopo" required/></label><label className="span-2">Conclusão<textarea name="conclusao" required/></label></>}
      {modal === "publicacao" && <><label>Código<input name="codigo" required defaultValue={proximo("PUB", dados.publicacoes)}/></label><label>Categoria<input name="categoria" required/></label><label>Período<input name="periodoReferencia"/></label><label className="span-2">Título<input name="titulo" required/></label><label className="span-2">Descrição pública<textarea name="descricaoPublica" required/></label></>}
    </div><footer><button type="button" onClick={() => setModal("")}>Cancelar</button><button className="sigiu-primary" disabled={salvando}>{salvando ? "Salvando…" : "Confirmar"}</button></footer></form></div>}
  </div>;
}

function LocalSelect({ unidades, padrao = "" }) { return <label>Local<select name="patrimonioUnidadeId" required defaultValue={padrao}><option value="">Selecione</option>{unidades.map((x) => <option key={x.id} value={x.id}>{titulo(x.nivel)} · {x.codigo} · {x.nome}</option>)}</select></label>; }
function PpciForm({ item, unidades, codigo, responsaveis }) { return <><LocalSelect unidades={unidades} padrao={item?.patrimonioUnidadeId}/><label>Código<input name="codigo" required defaultValue={item?.codigo || codigo}/></label><label className="span-2">Título<input name="titulo" required defaultValue={item?.titulo || ""}/></label><label>Nº processo / protocolo<input name="numeroProcesso" defaultValue={item?.numeroProcesso || ""}/></label><label>Órgão responsável<input name="orgaoResponsavel" defaultValue={item?.orgaoResponsavel || "Corpo de Bombeiros"}/></label><label>Ocupação<input name="ocupacao" defaultValue={item?.ocupacao || ""}/></label><label>Risco<select name="classificacaoRisco" defaultValue={item?.classificacaoRisco || "medio"}><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option><option value="especial">Especial</option></select></label><label>Área protegida (m²)<input name="areaProtegidaM2" type="number" min="0" step="0.01" defaultValue={item?.areaProtegidaM2 || ""}/></label><label>Fase<select name="fase" defaultValue={item?.fase || "levantamento"}><option value="levantamento">Levantamento</option><option value="projeto">Projeto</option><option value="protocolado">Protocolado</option><option value="analise">Análise</option><option value="exigencia">Exigência</option><option value="vistoria">Vistoria</option><option value="concluido">Concluído</option></select></label><label>Status<select name="status" defaultValue={item?.status || "em_elaboracao"}><option value="em_elaboracao">Em elaboração</option><option value="protocolado">Protocolado</option><option value="em_analise">Em análise</option><option value="exigencia">Exigência</option><option value="aprovado">Aprovado</option><option value="suspenso">Suspenso</option><option value="dispensado">Dispensado</option><option value="cancelado">Cancelado</option></select></label><label>Protocolo<input name="dataProtocolo" type="date" defaultValue={data(item?.dataProtocolo)}/></label><label>Aprovação<input name="dataAprovacao" type="date" defaultValue={data(item?.dataAprovacao)}/></label><label>Validade<input name="dataValidade" type="date" defaultValue={data(item?.dataValidade)}/></label><ResponsavelSelect responsaveis={responsaveis} defaultValue={item?.responsavel || ""}/><label className="span-2">Próximo passo<textarea name="proximoPasso" defaultValue={item?.proximoPasso || ""}/></label></>; }
