export const ROADMAP_PRUMO = [
  {
    id: "10.1",
    fase: "Fundação corporativa",
    tema: "Diagnóstico e arquitetura",
    status: "concluida",
    resumo: "Inventário do produto, contratos de API e preparação da transição local para corporativa.",
    entregas: ["Diagnóstico técnico", "Arquitetura multimódulo", "Plano de migração reversível"],
  },
  {
    id: "10.2",
    fase: "Fundação corporativa",
    tema: "Identidade e sessão",
    status: "concluida",
    resumo: "Perfis, sessão em memória, vínculos de empresa e preparação do provedor de identidade.",
    entregas: ["Perfis canônicos", "Contexto de empresa e equipe", "Contrato OIDC/JWT"],
  },
  {
    id: "10.3",
    fase: "Fundação corporativa",
    tema: "PostgreSQL e migração assistida",
    status: "concluida",
    resumo: "API executável, RLS multiempresa, fila e transição controlada dos repositórios.",
    entregas: ["PostgreSQL com RLS", "API corporativa", "Fila e worker", "Migração homologável"],
  },
  {
    id: "10.4",
    fase: "Governança da plataforma",
    tema: "Auditoria e recuperação",
    status: "concluida",
    resumo: "Trilha imutável, consulta, exportação, retenção, backup e restauração verificada.",
    entregas: ["Auditoria encadeada", "Política de retenção", "Backup verificado"],
  },
  {
    id: "10.5",
    fase: "Governança da plataforma",
    tema: "Documentos e integrações",
    status: "concluida",
    resumo: "Fundação corporativa do GED, versões, hashes, anexos e referências seguras de credenciais.",
    entregas: ["GED versionado", "Hash de integridade", "Integrações auditáveis"],
  },
  {
    id: "10.6",
    fase: "Governança da plataforma",
    tema: "Produto modular",
    status: "concluida",
    resumo: "Catálogo comercial, capacidades, dependências, contratos de módulos e perfis organizacionais.",
    entregas: ["Catálogo modular", "Licenciamento por organização", "Perfis operacionais"],
  },
  {
    id: "11",
    fase: "Fundação operacional",
    tema: "Patrimônio e espaços",
    status: "concluida",
    resumo: "Fonte corporativa única para Cliente, Site, Prédio, Sala, ativos e movimentações.",
    entregas: ["Hierarquia patrimonial", "Ativos e equipamentos", "Histórico de movimentações"],
  },
  {
    id: "12",
    fase: "Fundação operacional",
    tema: "Solicitações e investimentos",
    status: "concluida",
    resumo: "Solicitações, priorização ponderada, programas e carteira anual com aprovações.",
    entregas: ["Solicitações governadas", "Matriz de priorização", "Carteira de investimentos"],
  },
  {
    id: "12.1",
    fase: "Fundação operacional",
    tema: "Consolidação administrativa",
    status: "concluida",
    resumo: "Administração reorganizada como centro de governança e separada da operação cotidiana.",
    entregas: ["Administração por áreas", "Catálogo e permissões", "Operação técnica"],
  },
  {
    id: "13",
    fase: "Ciclo administrativo e financeiro",
    tema: "Suprimentos e contratações",
    status: "concluida",
    resumo: "Fornecedores, estudos, pesquisa de preços, julgamento, pedidos e recebimentos.",
    entregas: ["Cadastro de fornecedores", "Pesquisa e julgamento", "Pedidos e recebimentos"],
  },
  {
    id: "14",
    fase: "Ciclo administrativo e financeiro",
    tema: "Contratos e atas",
    status: "concluida",
    resumo: "Instrumentos, vigência, fiscalização, saldos, alterações, garantias e encerramento.",
    entregas: ["Gestão contratual", "Fiscalização", "Aditivos e sanções"],
  },
  {
    id: "15",
    fase: "Ciclo administrativo e financeiro",
    tema: "Financeiro-orçamentário",
    status: "concluida",
    resumo: "Centros, fontes, compromissos, liquidações, pagamentos, deduções e conciliação.",
    entregas: ["Planejamento financeiro", "Execução financeira", "Conciliação"],
  },
  {
    id: "16",
    fase: "Execução e operação",
    tema: "Obras e medições",
    status: "concluida",
    resumo: "Carteira corporativa, cronograma, diário, evidências, boletins e aceite.",
    entregas: ["Carteira de obras", "Cronograma e diário", "Medições corporativas"],
  },
  {
    id: "17",
    fase: "Execução e operação",
    tema: "Manutenção e facilities",
    status: "concluida",
    resumo: "Chamados, SLA, planos preventivos, ordens, recursos, fornecedores e custos.",
    entregas: ["Chamados e SLA", "Planos preventivos", "Ordens e custos"],
  },
  {
    id: "18",
    fase: "Prestação de contas e escala",
    tema: "Convênios e repasses",
    status: "concluida",
    resumo: "Instrumentos, metas, repasses, execução, diligências e prestação de contas.",
    entregas: ["Gestão de convênios", "Execução físico-financeira", "Prestação de contas"],
  },
  {
    id: "19",
    fase: "Prestação de contas e escala",
    tema: "Regularidade e compliance",
    status: "concluida",
    resumo: "Licenças, riscos, controles, auditorias, evidências e transparência autorizada.",
    entregas: ["Regularidade documental", "Riscos e controles", "Transparência"],
  },
  {
    id: "20",
    fase: "Prestação de contas e escala",
    tema: "BI, portais e consolidação",
    status: "concluida",
    resumo: "Indicadores executivos, relatórios configuráveis, portais, integrações e observabilidade.",
    entregas: ["Painel executivo", "Relatórios configuráveis", "Portais e integrações"],
  },
  {
    id: "20.1",
    fase: "Homologação e produto",
    tema: "Estabilização integrada",
    status: "concluida",
    resumo: "Uniformização da experiência, centralização do roadmap e tratamento dos achados de homologação.",
    entregas: ["Roadmap na Auditoria", "Telas sem rótulos de desenvolvimento", "Validação integrada"],
  },
  {
    id: "21",
    fase: "Homologação e produto",
    tema: "Contexto e homologação multiempresa",
    status: "concluida",
    resumo: "Contexto patrimonial global, exclusão segura e base reproduzível de homologação com três organizações isoladas.",
    entregas: [
      "Cliente ativo no banner",
      "Seletor hierárquico de Site, Prédio e Sala",
      "Correção da exclusão segura de Sites",
      "Base de homologação com três empresas fictícias",
    ],
  },
  {
    id: "22",
    fase: "Homologação e produto",
    tema: "Consolidação e prontidão local",
    status: "concluida",
    resumo: "Dados locais homologados no PostgreSQL, contexto propagado aos módulos compatíveis, carregamento sob demanda e validação ponta a ponta.",
    entregas: ["Lote local homologado", "Repositórios em modo híbrido", "Contexto propagado", "Carregamento modular", "Testes e build"],
  },
  {
    id: "23",
    fase: "Operação assistida",
    tema: "Piloto controlado e produção",
    status: "concluida",
    resumo: "Fundação de produção concluída com OIDC, storage GED S3 compatível, prontidão operacional, runbook de piloto e publicação controlada.",
    entregas: ["OIDC corporativo", "Upload e download seguro no GED", "Monitoramento e prontidão", "Guia de treinamento e piloto", "Plano de entrada em produção"],
  },
  {
    id: "24",
    fase: "Operação corporativa",
    tema: "Ambiente corporativo verificável",
    status: "concluida",
    resumo: "Prontidão de API, PostgreSQL, identidade, GED, segredos, recuperação, monitoramento e origens seguras governada por evidências.",
    entregas: ["Readiness com identidade", "Validação HTTPS", "Checklist por organização", "Evidências auditáveis"],
  },
  {
    id: "25",
    fase: "Operação corporativa",
    tema: "Migração definitiva e piloto assistido",
    status: "concluida",
    resumo: "Homologação, transição de repositórios, isolamento, retorno seguro e aceite do piloto submetidos a decisão administrativa bloqueante.",
    entregas: ["Governança da migração", "Piloto por organização", "Bloqueio de promoção prematura", "Decisões auditáveis"],
  },
  {
    id: "26",
    fase: "Segurança e produto",
    tema: "Acesso seguro e contingência",
    status: "concluida",
    resumo: "Acesso obrigatório, sessão curta e alternativa administrativa local protegida para indisponibilidade do provedor corporativo.",
    entregas: ["Tela de acesso", "Sessão assinada e revogável", "Contingência local protegida", "Limite de tentativas e registro de segurança"],
  },
  {
    id: "26.1",
    fase: "Segurança e produto",
    tema: "Consolidação funcional dos módulos",
    status: "concluida",
    resumo: "Navegação reorganizada para refletir o produto modular, sem duplicar funções correlatas em módulos independentes.",
    entregas: ["PPCI integrado à Regularidade", "Alertas integrados à Visão geral", "Bases integradas ao Orçamento", "Utilidades e consumos estratégicos"],
  },
  {
    id: "27",
    fase: "Execução contratual",
    tema: "Orçamento contratado e aditivos governados",
    status: "concluida",
    resumo: "O resultado da licitação gera uma base contratada imutável para medições, sem alterar o orçamento publicado; mudanças da obra seguem para análise da engenharia de custos.",
    entregas: ["Base contratada por desconto linear", "Orçamento publicado preservado", "Medições limitadas ao saldo contratado", "Solicitações de aditivo governadas"],
  },
  {
    id: "28",
    fase: "Informação técnica",
    tema: "Governança documental por entidade",
    status: "concluida",
    resumo: "Documentos passam a nascer ligados à entidade que lhes dá origem, com catálogo real, versões, revisão, aprovação e rastreabilidade corporativa.",
    entregas: ["Origem documental obrigatória", "Catálogo de entidades reais", "Fluxo de revisão e aprovação", "Filtros e vínculos auditáveis"],
  },
  {
    id: "29",
    fase: "Dados corporativos",
    tema: "Promoção verificável dos repositórios",
    status: "concluida",
    resumo: "Orçamentos somente adotam o PostgreSQL como fonte principal depois da comparação integral do acervo local homologado, com retorno controlado ao modo híbrido.",
    entregas: ["Manifesto SHA-256", "Paridade por quantidade e identificador", "Promoção bloqueante e versionada", "Retorno justificado e auditado"],
  },
  {
    id: "30",
    fase: "Regularidade patrimonial",
    tema: "PPCI local e segurança predial",
    status: "concluida",
    resumo: "PPCI deixa a fonte externa e passa ao PostgreSQL, consolidado com licenças, riscos e auditorias e ligado à árvore patrimonial.",
    entregas: ["PPCI local PostgreSQL", "Site, Prédio e Sala obrigatórios", "Sistemas ligados a ativos", "Inspeções imutáveis", "Painéis integrados"],
  },
  {
    id: "31",
    fase: "Operação patrimonial",
    tema: "PPCI operacional e utilidades mensuráveis",
    status: "concluida",
    resumo: "Sistemas PPCI passam a ser editáveis e removíveis com histórico preservado; o GED recebe vínculos contextuais e Utilidades ganha medidores e leituras PostgreSQL.",
    entregas: ["Edição e remoção rastreável no PPCI", "Responsáveis do cliente ativo", "PPCI integrado ao GED", "Medidores patrimoniais", "Leituras imutáveis", "Correções em Patrimônio e Solicitações"],
  },
  {
    id: "32",
    fase: "Operação de campo e manutenção",
    tema: "Leituras assistidas, patrimônio coerente e manutenção preventiva",
    status: "planejada",
    resumo: "Aprimora a operação de PPCI, simplifica a coleta de leituras, herda o endereço do Site e conecta planos periódicos dos ativos ao histórico de Manutenção.",
    entregas: ["PPCI responsivo e exclusões auditadas", "Leitura direta ou acumulada", "Coleta de campo simplificada", "Endereço patrimonial herdado", "Planos preventivos por ativo", "Histórico integrado à Manutenção"],
  },
];

export const STATUS_ROADMAP = {
  concluida: { rotulo: "Concluída", classe: "is-complete" },
  em_andamento: { rotulo: "Em andamento", classe: "is-current" },
  planejada: { rotulo: "Planejada", classe: "is-planned" },
};

export function agruparRoadmapPorFase(itens = ROADMAP_PRUMO) {
  return itens.reduce((fases, item) => {
    const fase = fases.find((grupo) => grupo.nome === item.fase);
    if (fase) fase.itens.push(item);
    else fases.push({ nome: item.fase, itens: [item] });
    return fases;
  }, []);
}
