export const MODULOS_PLATAFORMA = [
  { id: "visao-geral", nome: "Visão Geral", ordem: 10 },
  { id: "patrimonio", nome: "Patrimônio e Espaços", ordem: 15 },
  { id: "planejamento", nome: "Demandas e Investimentos", ordem: 18 },
  { id: "obras", nome: "Obras e Reformas", ordem: 20 },
  { id: "orcamentos", nome: "Orçamentos e Composições", ordem: 30 },
  { id: "bases-precos", nome: "Bases de Preços", ordem: 40 },
  { id: "suprimentos", nome: "Suprimentos e Aquisições", ordem: 50 },
  { id: "contratos", nome: "Contratos e Atas", ordem: 55 },
  { id: "financeiro", nome: "Financeiro-Orçamentário", ordem: 58 },
  { id: "medicoes", nome: "Medições e Fiscalização", ordem: 60 },
  { id: "manutencao", nome: "Manutenção", ordem: 70 },
  { id: "ppci", nome: "PPCI", ordem: 80 },
  { id: "regularidade", nome: "Regularidade e Compliance", ordem: 82 },
  { id: "utilidades", nome: "Consumos e Utilidades", ordem: 90 },
  { id: "documentos", nome: "Documentos e GED", ordem: 100 },
  { id: "convenios", nome: "Convênios e Repasses", ordem: 105 },
  { id: "relatorios", nome: "Relatórios", ordem: 110 },
  { id: "administracao", nome: "Administração", ordem: 120 },
];

export const PERMISSOES_PLATAFORMA = [
  { id: "plataforma.consultar", moduloId: "visao-geral" },
  { id: "patrimonio.consultar", moduloId: "patrimonio" },
  { id: "patrimonio.editar", moduloId: "patrimonio" },
  { id: "patrimonio.movimentar", moduloId: "patrimonio" },
  { id: "planejamento.consultar", moduloId: "planejamento" },
  { id: "planejamento.editar", moduloId: "planejamento" },
  { id: "planejamento.priorizar", moduloId: "planejamento" },
  { id: "planejamento.aprovar", moduloId: "planejamento" },
  { id: "empreendimento.consultar", moduloId: "obras" },
  { id: "empreendimento.editar", moduloId: "obras" },
  { id: "obras.consultar", moduloId: "obras" },
  { id: "obras.editar", moduloId: "obras" },
  { id: "obras.fiscalizar", moduloId: "obras" },
  { id: "orcamento.consultar", moduloId: "orcamentos" },
  { id: "orcamento.editar", moduloId: "orcamentos" },
  { id: "orcamento.revisar", moduloId: "orcamentos" },
  { id: "orcamento.aprovar", moduloId: "orcamentos" },
  { id: "bases.consultar", moduloId: "bases-precos" },
  { id: "bases.administrar", moduloId: "bases-precos" },
  { id: "suprimentos.consultar", moduloId: "suprimentos" },
  { id: "suprimentos.editar", moduloId: "suprimentos" },
  { id: "suprimentos.cotar", moduloId: "suprimentos" },
  { id: "suprimentos.julgar", moduloId: "suprimentos" },
  { id: "suprimentos.aprovar", moduloId: "suprimentos" },
  { id: "suprimentos.receber", moduloId: "suprimentos" },
  { id: "contratos.consultar", moduloId: "contratos" },
  { id: "contratos.editar", moduloId: "contratos" },
  { id: "contratos.gerir", moduloId: "contratos" },
  { id: "contratos.fiscalizar", moduloId: "contratos" },
  { id: "contratos.sancionar", moduloId: "contratos" },
  { id: "contratos.encerrar", moduloId: "contratos" },
  { id: "financeiro.consultar", moduloId: "financeiro" },
  { id: "financeiro.planejar", moduloId: "financeiro" },
  { id: "financeiro.comprometer", moduloId: "financeiro" },
  { id: "financeiro.liquidar", moduloId: "financeiro" },
  { id: "financeiro.pagar", moduloId: "financeiro" },
  { id: "financeiro.conciliar", moduloId: "financeiro" },
  { id: "medicao.consultar", moduloId: "medicoes" },
  { id: "medicao.registrar", moduloId: "medicoes" },
  { id: "medicao.aprovar", moduloId: "medicoes" },
  { id: "manutencao.consultar", moduloId: "manutencao" },
  { id: "manutencao.editar", moduloId: "manutencao" },
  { id: "manutencao.planejar", moduloId: "manutencao" },
  { id: "manutencao.atender", moduloId: "manutencao" },
  { id: "manutencao.encerrar", moduloId: "manutencao" },
  { id: "ppci.consultar", moduloId: "ppci" },
  { id: "ppci.editar", moduloId: "ppci" },
  { id: "regularidade.consultar", moduloId: "regularidade" },
  { id: "regularidade.editar", moduloId: "regularidade" },
  { id: "regularidade.auditar", moduloId: "regularidade" },
  { id: "transparencia.publicar", moduloId: "regularidade" },
  { id: "utilidades.consultar", moduloId: "utilidades" },
  { id: "documentos.consultar", moduloId: "documentos" },
  { id: "documentos.editar", moduloId: "documentos" },
  { id: "documentos.aprovar", moduloId: "documentos" },
  { id: "convenios.consultar", moduloId: "convenios" },
  { id: "convenios.editar", moduloId: "convenios" },
  { id: "convenios.executar", moduloId: "convenios" },
  { id: "convenios.prestar-contas", moduloId: "convenios" },
  { id: "relatorios.consultar", moduloId: "relatorios" },
  { id: "relatorios.configurar", moduloId: "relatorios" },
  { id: "portais.consultar", moduloId: "relatorios" },
  { id: "portais.administrar", moduloId: "relatorios" },
  { id: "administracao.acessar", moduloId: "administracao" },
  { id: "auditoria.consultar", moduloId: "administracao" },
  { id: "auditoria.administrar", moduloId: "administracao" },
  { id: "integracoes.consultar", moduloId: "administracao" },
  { id: "integracoes.administrar", moduloId: "administracao" },
  { id: "observabilidade.consultar", moduloId: "administracao" },
  { id: "piloto.consultar", moduloId: "administracao" },
  { id: "piloto.administrar", moduloId: "administracao" },
  { id: "produto-modular.consultar", moduloId: "administracao" },
  { id: "produto-modular.administrar", moduloId: "administracao" },
  { id: "migracao.administrar", moduloId: "administracao" },
  { id: "trabalho.consultar", moduloId: "administracao" },
  { id: "trabalho.administrar", moduloId: "administracao" },
  { id: "repositorio.transicionar", moduloId: "administracao" },
];

const LEITURA = PERMISSOES_PLATAFORMA
  .filter((item) => item.id.endsWith(".consultar") || item.id === "plataforma.consultar")
  .map((item) => item.id);

export const PERMISSOES_PADRAO_POR_PERFIL = {
  administrador: PERMISSOES_PLATAFORMA.map((item) => item.id),
  gestor: [
    ...LEITURA,
    "empreendimento.editar",
    "obras.editar",
    "obras.fiscalizar",
    "planejamento.editar",
    "planejamento.priorizar",
    "orcamento.editar",
    "orcamento.revisar",
    "orcamento.aprovar",
    "suprimentos.editar",
    "suprimentos.cotar",
    "suprimentos.julgar",
    "suprimentos.aprovar",
    "suprimentos.receber",
    "contratos.editar",
    "contratos.gerir",
    "contratos.fiscalizar",
    "contratos.encerrar",
    "financeiro.planejar",
    "financeiro.comprometer",
    "financeiro.liquidar",
    "regularidade.auditar",
    "convenios.executar",
    "medicao.registrar",
    "medicao.aprovar",
    "manutencao.planejar",
    "manutencao.atender",
    "manutencao.encerrar",
    "documentos.editar",
    "documentos.aprovar",
    "convenios.prestar-contas",
    "transparencia.publicar",
    "portais.consultar",
    "regularidade.editar",
    "regularidade.auditar",
    "convenios.editar",
    "convenios.executar",
    "convenios.prestar-contas",
    "relatorios.configurar",
    "portais.consultar",
    "portais.administrar",
    "auditoria.consultar",
    "integracoes.consultar",
    "produto-modular.consultar",
    "observabilidade.consultar",
    "piloto.consultar",
  ],
  orcamentista: [
    "plataforma.consultar",
    "planejamento.consultar",
    "empreendimento.consultar",
    "obras.consultar",
    "orcamento.consultar",
    "orcamento.editar",
    "orcamento.revisar",
    "bases.consultar",
    "suprimentos.consultar",
    "suprimentos.cotar",
    "contratos.consultar",
    "financeiro.consultar",
    "documentos.consultar",
  ],
  fiscal: [
    "plataforma.consultar",
    "planejamento.consultar",
    "empreendimento.consultar",
    "obras.consultar",
    "orcamento.consultar",
    "medicao.consultar",
    "medicao.registrar",
    "obras.fiscalizar",
    "manutencao.consultar",
    "manutencao.atender",
    "contratos.fiscalizar",
    "financeiro.consultar",
    "financeiro.liquidar",
    "documentos.consultar",
    "documentos.editar",
  ],
  aprovador: [
    "plataforma.consultar",
    "empreendimento.consultar",
    "obras.consultar",
    "planejamento.consultar",
    "planejamento.aprovar",
    "orcamento.consultar",
    "orcamento.aprovar",
    "medicao.consultar",
    "medicao.aprovar",
    "contratos.gerir",
    "contratos.sancionar",
    "contratos.encerrar",
    "financeiro.comprometer",
    "financeiro.liquidar",
    "financeiro.pagar",
    "financeiro.conciliar",
    "documentos.consultar",
    "documentos.aprovar",
    "auditoria.consultar",
  ],
  consulta: LEITURA,
};

export function obterPermissoesPerfil(perfilId) {
  return [...(PERMISSOES_PADRAO_POR_PERFIL[perfilId] || [])];
}

export function obterModulosPermitidos(permissoes = [], modulosAtivos = MODULOS_PLATAFORMA) {
  const ids = new Set(
    PERMISSOES_PLATAFORMA
      .filter((permissao) => permissoes.includes(permissao.id))
      .map((permissao) => permissao.moduloId),
  );
  return modulosAtivos.filter((modulo) => ids.has(modulo.id));
}
